"""initial schema

Revision ID: 079e2229e15e
Revises: 
Create Date: 2026-05-31 21:35:10.191304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079e2229e15e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('commands_total', sa.Integer(), nullable=False),
    sa.Column('commands_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmaker_markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_event_id', sa.String(length=100), nullable=False),
    sa.Column('bookmaker_market_key', sa.String(length=200), nullable=False),
    sa.Column('market_name', sa.String(length=200), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('line_id', sa.String(length=50), nullable=True),
    sa.Column('line_name', sa.String(length=200), nullable=True),
    sa.Column('is_extra_market', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmaker_event_id', 'bookmaker_market_key')
    )
    op.create_index(op.f('ix_bookmaker_markets_bookmaker_event_id'), 'bookmaker_markets', ['bookmaker_event_id'], unique=False)
    op.create_table('bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('canonical_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('team_a_name', sa.String(length=200), nullable=False),
    sa.Column('team_b_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_team_a', sa.String(length=200), nullable=False),
    sa.Column('normalized_team_b', sa.String(length=200), nullable=False),
    sa.Column('start_time_normalized', sa.String(length=50), nullable=True),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('match_confidence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_table('golgg_matches',
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('tournament_name', sa.String(length=300), nullable=True),
    sa.Column('patch', sa.String(length=20), nullable=True),
    sa.Column('team1_name', sa.String(length=200), nullable=True),
    sa.Column('team2_name', sa.String(length=200), nullable=True),
    sa.Column('team1_id', sa.String(length=50), nullable=True),
    sa.Column('team2_id', sa.String(length=50), nullable=True),
    sa.Column('team1_score', sa.Integer(), nullable=True),
    sa.Column('team2_score', sa.Integer(), nullable=True),
    sa.Column('team1_win', sa.Integer(), nullable=True),
    sa.Column('team2_win', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('best_of', sa.Integer(), nullable=True),
    sa.Column('winner_name', sa.String(length=200), nullable=True),
    sa.Column('loser_name', sa.String(length=200), nullable=True),
    sa.Column('source_link', sa.String(length=500), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('golgg_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('normalized_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('feature_schema_json', sa.Text(), nullable=True),
    sa.Column('model_params_json', sa.Text(), nullable=True),
    sa.Column('training_cutoff_at', sa.String(length=50), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'model_version')
    )
    op.create_table('rating_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ratings_version', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('data_cutoff_at', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('systems_json', sa.Text(), nullable=True),
    sa.Column('matches_processed', sa.Integer(), nullable=False),
    sa.Column('games_processed', sa.Integer(), nullable=False),
    sa.Column('players_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ratings_version')
    )
    op.create_table('team_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'source')
    )
    op.create_table('team_rolling_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_version', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_team_name', sa.String(length=200), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('data_cutoff_at', sa.String(length=50), nullable=True),
    sa.Column('matches_count', sa.Integer(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.Column('avg_kills', sa.Integer(), nullable=True),
    sa.Column('avg_deaths', sa.Integer(), nullable=True),
    sa.Column('avg_gd15', sa.Integer(), nullable=True),
    sa.Column('avg_dpm', sa.Integer(), nullable=True),
    sa.Column('avg_vspm', sa.Integer(), nullable=True),
    sa.Column('avg_gold', sa.Integer(), nullable=True),
    sa.Column('avg_towers', sa.Integer(), nullable=True),
    sa.Column('avg_dragons', sa.Integer(), nullable=True),
    sa.Column('avg_nashors', sa.Integer(), nullable=True),
    sa.Column('avg_game_duration', sa.Integer(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_version', 'normalized_team_name', 'window_size')
    )
    op.create_index(op.f('ix_team_rolling_features_feature_version'), 'team_rolling_features', ['feature_version'], unique=False)
    op.create_table('automation_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmaker_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmaker_id', 'account_name')
    )
    op.create_table('bookmaker_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_event_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_match_id', sa.Integer(), nullable=True),
    sa.Column('raw_team_a', sa.String(length=200), nullable=False),
    sa.Column('raw_team_b', sa.String(length=200), nullable=False),
    sa.Column('match_start_time', sa.String(length=50), nullable=True),
    sa.Column('sport_id', sa.String(length=20), nullable=True),
    sa.Column('sport_name', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.String(length=20), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('league_id', sa.String(length=20), nullable=True),
    sa.Column('league_name', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.String(length=50), nullable=True),
    sa.Column('offer_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmaker_id', 'bookmaker_event_id')
    )
    op.create_table('canonical_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_match_id', sa.Integer(), nullable=False),
    sa.Column('model_artifact_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.String(length=50), nullable=True),
    sa.Column('prob_a', sa.Integer(), nullable=True),
    sa.Column('prob_b', sa.Integer(), nullable=True),
    sa.Column('features_version', sa.String(length=100), nullable=True),
    sa.Column('ratings_version', sa.String(length=100), nullable=True),
    sa.Column('data_cutoff_at', sa.String(length=50), nullable=True),
    sa.Column('prediction_status', sa.String(length=50), nullable=False),
    sa.Column('diagnostics_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_predictions_canonical_match_id'), 'canonical_predictions', ['canonical_match_id'], unique=False)
    op.create_table('entity_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating_run_id', sa.Integer(), nullable=True),
    sa.Column('ratings_version', sa.String(length=100), nullable=False),
    sa.Column('snapshot_at', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_entity_name', sa.String(length=200), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('rating_system', sa.String(length=20), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=True),
    sa.Column('rd', sa.Integer(), nullable=True),
    sa.Column('sigma', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('last_match_at', sa.String(length=50), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rating_run_id'], ['rating_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ratings_version', 'entity_type', 'normalized_entity_name', 'rating_system')
    )
    op.create_index(op.f('ix_entity_ratings_entity_type'), 'entity_ratings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_ratings_normalized_entity_name'), 'entity_ratings', ['normalized_entity_name'], unique=False)
    op.create_index(op.f('ix_entity_ratings_rating_system'), 'entity_ratings', ['rating_system'], unique=False)
    op.create_index(op.f('ix_entity_ratings_ratings_version'), 'entity_ratings', ['ratings_version'], unique=False)
    op.create_table('golgg_games',
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('tournament_name', sa.String(length=300), nullable=True),
    sa.Column('patch', sa.String(length=20), nullable=True),
    sa.Column('team1_name', sa.String(length=200), nullable=True),
    sa.Column('team2_name', sa.String(length=200), nullable=True),
    sa.Column('team1_id', sa.String(length=50), nullable=True),
    sa.Column('team2_id', sa.String(length=50), nullable=True),
    sa.Column('team1_win', sa.Integer(), nullable=True),
    sa.Column('team2_win', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('team1_side', sa.String(length=10), nullable=True),
    sa.Column('team2_side', sa.String(length=10), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('team1_stats_json', sa.Text(), nullable=True),
    sa.Column('team2_stats_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['golgg_matches.match_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_golgg_games_match_id'), 'golgg_games', ['match_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('canonical_match_id', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('raw_team_a', sa.String(length=200), nullable=True),
    sa.Column('raw_team_b', sa.String(length=200), nullable=True),
    sa.Column('odds_a', sa.Integer(), nullable=True),
    sa.Column('odds_b', sa.Integer(), nullable=True),
    sa.Column('is_live', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('offer_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_bookmaker_id'), 'odds_snapshots', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_canonical_match_id'), 'odds_snapshots', ['canonical_match_id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_scraped_at'), 'odds_snapshots', ['scraped_at'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('scraper_name', sa.String(length=100), nullable=False),
    sa.Column('scraper_version', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('finished_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('request_url', sa.String(length=500), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upcoming_match_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_match_id', sa.Integer(), nullable=False),
    sa.Column('feature_version', sa.String(length=100), nullable=False),
    sa.Column('ratings_version', sa.String(length=100), nullable=False),
    sa.Column('data_cutoff_at', sa.String(length=50), nullable=True),
    sa.Column('team_a_golgg_name', sa.String(length=200), nullable=True),
    sa.Column('team_b_golgg_name', sa.String(length=200), nullable=True),
    sa.Column('feature_status', sa.String(length=50), nullable=False),
    sa.Column('missing_reason', sa.Text(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_match_id', 'feature_version', 'ratings_version')
    )
    op.create_table('upcoming_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_match_key', sa.String(length=200), nullable=False),
    sa.Column('canonical_match_id', sa.Integer(), nullable=True),
    sa.Column('raw_team_a', sa.String(length=200), nullable=False),
    sa.Column('raw_team_b', sa.String(length=200), nullable=False),
    sa.Column('normalized_team_a', sa.String(length=200), nullable=False),
    sa.Column('normalized_team_b', sa.String(length=200), nullable=False),
    sa.Column('match_start_time', sa.String(length=50), nullable=True),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('offer_url', sa.String(length=500), nullable=True),
    sa.Column('is_live', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bookmaker_match_key')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('model_ev_signal_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_account_id', sa.Integer(), nullable=True),
    sa.Column('canonical_match_id', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taken_odds', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('team_a', sa.String(length=200), nullable=True),
    sa.Column('team_b', sa.String(length=200), nullable=True),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('match_start_time', sa.DateTime(), nullable=True),
    sa.Column('model_prob', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ev', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_account_id'], ['bookmaker_accounts.id'], ),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golgg_game_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.String(length=50), nullable=True),
    sa.Column('team_name', sa.String(length=200), nullable=True),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('player_id', sa.String(length=50), nullable=True),
    sa.Column('player_name', sa.String(length=200), nullable=True),
    sa.Column('champion_id', sa.String(length=50), nullable=True),
    sa.Column('champion_name', sa.String(length=100), nullable=True),
    sa.Column('champion_image', sa.String(length=500), nullable=True),
    sa.Column('stats_json', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['golgg_games.game_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['golgg_matches.match_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'side', 'role')
    )
    op.create_index(op.f('ix_golgg_game_players_game_id'), 'golgg_game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_golgg_game_players_match_id'), 'golgg_game_players', ['match_id'], unique=False)
    op.create_index(op.f('ix_golgg_game_players_player_id'), 'golgg_game_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_golgg_game_players_side'), 'golgg_game_players', ['side'], unique=False)
    op.create_table('model_ev_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_match_id', sa.Integer(), nullable=False),
    sa.Column('canonical_prediction_id', sa.Integer(), nullable=True),
    sa.Column('odds_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('model_prob', sa.Integer(), nullable=True),
    sa.Column('market_prob', sa.Integer(), nullable=True),
    sa.Column('ev', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('stake_suggestion', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmakers.id'], ),
    sa.ForeignKeyConstraint(['canonical_match_id'], ['canonical_matches.id'], ),
    sa.ForeignKeyConstraint(['canonical_prediction_id'], ['canonical_predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_ev_signals_canonical_match_id'), 'model_ev_signals', ['canonical_match_id'], unique=False)
    op.create_table('odds_outcome_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_event_id', sa.String(length=100), nullable=False),
    sa.Column('bookmaker_market_key', sa.String(length=200), nullable=False),
    sa.Column('outcome_key', sa.String(length=200), nullable=False),
    sa.Column('scraped_at', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('offer_url', sa.String(length=500), nullable=True),
    sa.Column('outcome_name', sa.String(length=200), nullable=True),
    sa.Column('outcome_side', sa.String(length=10), nullable=True),
    sa.Column('decimal_odds', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scrape_run_id', 'outcome_key')
    )
    op.create_index(op.f('ix_odds_outcome_snapshots_bookmaker_event_id'), 'odds_outcome_snapshots', ['bookmaker_event_id'], unique=False)
    op.create_index(op.f('ix_odds_outcome_snapshots_bookmaker_market_key'), 'odds_outcome_snapshots', ['bookmaker_market_key'], unique=False)
    op.create_index(op.f('ix_odds_outcome_snapshots_scraped_at'), 'odds_outcome_snapshots', ['scraped_at'], unique=False)
    op.create_table('bookmaker_wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_account_id', sa.Integer(), nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['bookmaker_account_id'], ['bookmaker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmaker_wallet_transactions')
    op.drop_index(op.f('ix_odds_outcome_snapshots_scraped_at'), table_name='odds_outcome_snapshots')
    op.drop_index(op.f('ix_odds_outcome_snapshots_bookmaker_market_key'), table_name='odds_outcome_snapshots')
    op.drop_index(op.f('ix_odds_outcome_snapshots_bookmaker_event_id'), table_name='odds_outcome_snapshots')
    op.drop_table('odds_outcome_snapshots')
    op.drop_index(op.f('ix_model_ev_signals_canonical_match_id'), table_name='model_ev_signals')
    op.drop_table('model_ev_signals')
    op.drop_index(op.f('ix_golgg_game_players_side'), table_name='golgg_game_players')
    op.drop_index(op.f('ix_golgg_game_players_player_id'), table_name='golgg_game_players')
    op.drop_index(op.f('ix_golgg_game_players_match_id'), table_name='golgg_game_players')
    op.drop_index(op.f('ix_golgg_game_players_game_id'), table_name='golgg_game_players')
    op.drop_table('golgg_game_players')
    op.drop_table('bets')
    op.drop_table('upcoming_matches')
    op.drop_table('upcoming_match_features')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_odds_snapshots_scraped_at'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_canonical_match_id'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_bookmaker_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_golgg_games_match_id'), table_name='golgg_games')
    op.drop_table('golgg_games')
    op.drop_index(op.f('ix_entity_ratings_ratings_version'), table_name='entity_ratings')
    op.drop_index(op.f('ix_entity_ratings_rating_system'), table_name='entity_ratings')
    op.drop_index(op.f('ix_entity_ratings_normalized_entity_name'), table_name='entity_ratings')
    op.drop_index(op.f('ix_entity_ratings_entity_type'), table_name='entity_ratings')
    op.drop_table('entity_ratings')
    op.drop_index(op.f('ix_canonical_predictions_canonical_match_id'), table_name='canonical_predictions')
    op.drop_table('canonical_predictions')
    op.drop_table('bookmaker_events')
    op.drop_table('bookmaker_accounts')
    op.drop_table('automation_commands')
    op.drop_index(op.f('ix_team_rolling_features_feature_version'), table_name='team_rolling_features')
    op.drop_table('team_rolling_features')
    op.drop_table('team_aliases')
    op.drop_table('rating_runs')
    op.drop_table('model_artifacts')
    op.drop_table('golgg_teams')
    op.drop_table('golgg_matches')
    op.drop_table('canonical_matches')
    op.drop_table('bookmakers')
    op.drop_index(op.f('ix_bookmaker_markets_bookmaker_event_id'), table_name='bookmaker_markets')
    op.drop_table('bookmaker_markets')
    op.drop_table('automation_runs')
    # ### end Alembic commands ###
