"""Create final thesis comparison for Logistic Regression W20-Binomial.

The script aligns W20-Binomial walk-forward predictions with bookmaker market
benchmarks on the common GOL.GG--OddsPortal sample. It reports final thesis
metrics and monthly block-bootstrap differences in LogLoss.
"""

from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score

from src.visualization.thesis_style import (
    DARK_TEXT,
    PASTEL_BLUE,
    PASTEL_ORANGE,
    apply_thesis_style,
    clean_axis,
    colors_for,
)

SOURCE_COMPARISON_DIR = PROJECT_ROOT / "docs" / "assets" / "final_model_market_comparison"
MODEL_DIR = PROJECT_ROOT / "docs" / "assets" / "w20_binomial_all_models_bootstrap"
OUTPUT_DIR = PROJECT_ROOT / "docs" / "assets" / "final_w20_binomial_market_comparison"
TARGET = "y_true"
N_BOOTSTRAPS = 10000
RANDOM_SEED = 42
FINAL_MODEL = "Logistic Regression ElasticNet W20-Binomial"

MODEL_VARIANTS = {
    "LR-ElasticNet-W20-Binomial": FINAL_MODEL,
    "ExtraTrees-W20-Binomial": "ExtraTrees W20-Binomial",
    "LightGBM-W20-Binomial": "LightGBM W20-Binomial",
    "HGB-W20-Binomial": "HistGradientBoosting W20-Binomial",
    "MLP-W20-Binomial": "MLP W20-Binomial",
}


def calculate_ece(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> float:
    """Calculate expected calibration error for binary probabilities.

    Args:
        y_true: Binary target labels.
        y_prob: Predicted positive-class probabilities.
        n_bins: Number of equal-width probability bins.

    Returns:
        Weighted average absolute calibration error.
    """

    boundaries = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for lower, upper in zip(boundaries[:-1], boundaries[1:]):
        in_bin = (y_prob > lower) & (y_prob <= upper)
        weight = float(np.mean(in_bin))
        if weight == 0.0:
            continue
        ece += abs(float(np.mean(y_true[in_bin])) - float(np.mean(y_prob[in_bin]))) * weight
    return ece


def safe_column_name(model_name: str) -> str:
    """Create a stable probability column name from a model label.

    Args:
        model_name: Human-readable model name.

    Returns:
        Lowercase probability column identifier.
    """

    return "prob_" + (
        model_name.lower()
        .replace(" ", "_")
        .replace("-", "_")
        .replace("+", "plus")
        .replace("/", "_")
    )


def evaluate_probability(data: pd.DataFrame, model: str, column: str) -> dict[str, object]:
    """Evaluate one probability column on the common sample.

    Args:
        data: DataFrame containing target and probability columns.
        model: Human-readable model name.
        column: Probability column to evaluate.

    Returns:
        Dictionary with thesis metrics.
    """

    subset = data[[TARGET, column]].dropna().copy()
    y_true = subset[TARGET].astype(int).to_numpy()
    y_prob = np.clip(subset[column].to_numpy(dtype=float), 0.001, 0.999)
    return {
        "model": model,
        "probability_column": column,
        "sample_size": int(len(subset)),
        "auc": float(roc_auc_score(y_true, y_prob)),
        "logloss": float(log_loss(y_true, y_prob)),
        "brier": float(brier_score_loss(y_true, y_prob)),
        "ece": calculate_ece(y_true, y_prob),
    }


def load_variant(predictions: pd.DataFrame, variant: str, column: str) -> pd.DataFrame:
    """Extract one model variant from long prediction output.

    Args:
        predictions: Long prediction table generated by EXP-030.
        variant: Variant label to select.
        column: Output probability column name.

    Returns:
        Match ID and selected probability column.
    """

    selected = predictions.loc[predictions["variant"] == variant, ["golgg_match_id", "y_prob"]].copy()
    selected["golgg_match_id"] = selected["golgg_match_id"].astype(str)
    return selected.rename(columns={"y_prob": column})


def log_loss_vector(y_true: np.ndarray, y_prob: np.ndarray) -> np.ndarray:
    """Return per-match binary LogLoss values.

    Args:
        y_true: Binary target labels.
        y_prob: Predicted positive-class probabilities.

    Returns:
        Vector of per-row LogLoss values.
    """

    clipped = np.clip(y_prob.astype(float), 1e-15, 1.0 - 1e-15)
    labels = y_true.astype(int)
    return -(labels * np.log(clipped) + (1 - labels) * np.log(1 - clipped))


def monthly_block_bootstrap(data: pd.DataFrame, main_column: str) -> pd.DataFrame:
    """Compare the final W20-Binomial model with monthly block bootstrap.

    Positive differences mean that the final model has lower LogLoss than the
    benchmark.

    Args:
        data: Common sample with target, dates and probability columns.
        main_column: Probability column for the final W20-Binomial model.

    Returns:
        Bootstrap summary table.
    """

    comparisons = {
        "Mkt Open": "market_open",
        "Mkt Close": "market_close",
        "Player Glicko-2": "player_glicko2",
        "ExtraTrees-W20-Binomial": safe_column_name("ExtraTrees-W20-Binomial"),
        "LightGBM-W20-Binomial": safe_column_name("LightGBM-W20-Binomial"),
        "HGB-W20-Binomial": safe_column_name("HGB-W20-Binomial"),
        "MLP-W20-Binomial": safe_column_name("MLP-W20-Binomial"),
    }
    working = data.copy()
    working["month"] = pd.to_datetime(working["date"]).dt.to_period("M").astype(str)
    months = sorted(working["month"].unique())
    y_true = working[TARGET].astype(int).to_numpy()
    main_loss = log_loss_vector(y_true, working[main_column].to_numpy())
    rng = np.random.default_rng(RANDOM_SEED)
    rows: list[dict[str, object]] = []
    for label, column in comparisons.items():
        benchmark_loss = log_loss_vector(y_true, working[column].to_numpy())
        working["delta"] = benchmark_loss - main_loss
        observed = float(working["delta"].mean())
        month_stats = working.groupby("month")["delta"].agg(delta_sum="sum", n="size").loc[months]
        delta_sums = month_stats["delta_sum"].to_numpy(dtype=float)
        counts = month_stats["n"].to_numpy(dtype=float)
        samples = np.empty(N_BOOTSTRAPS, dtype=float)
        for idx in range(N_BOOTSTRAPS):
            sampled_idx = rng.integers(0, len(months), size=len(months))
            samples[idx] = delta_sums[sampled_idx].sum() / counts[sampled_idx].sum()
        rows.append(
            {
                "comparison": f"LR-ElasticNet-W20-Binomial vs {label}",
                "observed_delta_logloss": observed,
                "ci_lower_95": float(np.quantile(samples, 0.025)),
                "ci_upper_95": float(np.quantile(samples, 0.975)),
                "p_one_sided_final_model_better": float((np.sum(samples <= 0.0) + 1) / (len(samples) + 1)),
                "significantly_better": bool(np.quantile(samples, 0.025) > 0.0),
            }
        )
    return pd.DataFrame(rows).sort_values("observed_delta_logloss", ascending=False)


def plot_metric(metrics: pd.DataFrame, metric: str, file_name: str, ylabel: str) -> None:
    """Create bar plot for one final metric.

    Args:
        metrics: Metrics table.
        metric: Metric column to plot.
        file_name: Output PNG file name.
        ylabel: Axis label.
    """

    plot_data = metrics.copy()
    apply_thesis_style(context="paper")
    colors = colors_for(plot_data["model"].tolist())
    fig, ax = plt.subplots(figsize=(12.2, 6.4))
    bars = ax.bar(plot_data["model"], plot_data[metric], color=colors[: len(plot_data)], edgecolor="white")
    ax.set_ylabel(ylabel, fontsize=13)
    ax.set_title(f"Końcowe porównanie według {metric.upper()}", fontsize=16, pad=14)
    ax.tick_params(axis="x", labelrotation=25, labelsize=10)
    for label in ax.get_xticklabels():
        label.set_horizontalalignment("right")
        label.set_rotation_mode("anchor")
    values = plot_data[metric].to_numpy()
    margin = max((values.max() - values.min()) * 0.35, 0.002)
    if metric == "ece":
        ax.set_ylim(0.0, values.max() * 1.25)
    else:
        ax.set_ylim(values.min() - margin, values.max() + margin)
    for bar, value in zip(bars, values):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value + (ax.get_ylim()[1] - ax.get_ylim()[0]) * 0.015,
            f"{value:.4f}",
            ha="center",
            va="bottom",
            fontsize=9,
        )
    clean_axis(ax)
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / file_name, dpi=180)
    plt.close(fig)


def plot_bootstrap(bootstrap: pd.DataFrame) -> None:
    """Save confidence-interval plot for final-model comparisons."""

    plot_data = bootstrap.sort_values("observed_delta_logloss").copy()
    fig, ax = plt.subplots(figsize=(11.6, 6.0))
    y_positions = np.arange(len(plot_data))
    ax.errorbar(
        plot_data["observed_delta_logloss"],
        y_positions,
        xerr=[
            plot_data["observed_delta_logloss"] - plot_data["ci_lower_95"],
            plot_data["ci_upper_95"] - plot_data["observed_delta_logloss"],
        ],
        fmt="o",
        color=PASTEL_BLUE,
        ecolor=PASTEL_ORANGE,
        elinewidth=1.4,
        capsize=4,
    )
    ax.axvline(0.0, color=DARK_TEXT, linestyle="--", linewidth=1)
    ax.set_yticks(y_positions)
    ax.set_yticklabels(plot_data["comparison"].str.replace("LR-ElasticNet-W20-Binomial vs ", "", regex=False))
    ax.set_xlabel("Różnica LogLoss względem LR-ElasticNet-W20-Binomial")
    ax.set_title("Monthly block bootstrap — finalny model vs benchmarki")
    clean_axis(ax, grid_axis="x")
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "final_w20_binomial_market_bootstrap_ci.png", dpi=180)
    plt.close(fig)


def main() -> None:
    """Build final W20-Binomial-versus-market thesis artefacts."""

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    common = pd.read_csv(SOURCE_COMPARISON_DIR / "final_model_market_common_sample.csv")
    common["golgg_match_id"] = common["golgg_match_id"].astype(str)

    predictions = pd.read_csv(MODEL_DIR / "all_models_predictions.csv")
    predictions["golgg_match_id"] = predictions["golgg_match_id"].astype(str)

    probability_columns: dict[str, str] = {}
    for short_name, variant_name in MODEL_VARIANTS.items():
        column = safe_column_name(short_name)
        common = common.merge(load_variant(predictions, variant_name, column), on="golgg_match_id", how="inner")
        probability_columns[short_name] = column

    metrics = pd.DataFrame(
        [
            evaluate_probability(common, "LR-ElasticNet-W20-Binomial", probability_columns["LR-ElasticNet-W20-Binomial"]),
            evaluate_probability(common, "ExtraTrees-W20-Binomial", probability_columns["ExtraTrees-W20-Binomial"]),
            evaluate_probability(common, "LightGBM-W20-Binomial", probability_columns["LightGBM-W20-Binomial"]),
            evaluate_probability(common, "HGB-W20-Binomial", probability_columns["HGB-W20-Binomial"]),
            evaluate_probability(common, "MLP-W20-Binomial", probability_columns["MLP-W20-Binomial"]),
            evaluate_probability(common, "Player Glicko-2", "player_glicko2"),
            evaluate_probability(common, "Mkt Close", "market_close"),
            evaluate_probability(common, "Mkt Open", "market_open"),
        ]
    ).sort_values("logloss")
    bootstrap = monthly_block_bootstrap(common, probability_columns["LR-ElasticNet-W20-Binomial"])

    common.to_csv(OUTPUT_DIR / "final_w20_binomial_market_common_sample.csv", index=False)
    metrics.to_csv(OUTPUT_DIR / "final_w20_binomial_market_metrics.csv", index=False)
    bootstrap.to_csv(OUTPUT_DIR / "final_w20_binomial_market_bootstrap.csv", index=False)

    plot_metric(metrics, "logloss", "final_w20_binomial_market_logloss.png", "LogLoss (niżej = lepiej)")
    plot_metric(metrics, "auc", "final_w20_binomial_market_auc.png", "AUC (wyżej = lepiej)")
    plot_metric(metrics, "ece", "final_w20_binomial_market_ece.png", "ECE (niżej = lepiej)")
    plot_bootstrap(bootstrap)

    print("\n=== FINAL W20-BINOMIAL MODEL VS MARKET COMPARISON ===")
    print("Common sample size:", len(common))
    print(metrics.to_string(index=False))
    print("\n=== MONTHLY BLOCK BOOTSTRAP VS LR-ELASTICNET-W20-BINOMIAL ===")
    print(bootstrap.to_string(index=False))
    print("\nSaved artefacts to:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
