"""Evaluate leakage-safe calibration for standard and symmetrized predictions.

The script uses out-of-time walk-forward predictions generated by
``06ag_team_order_sensitivity_analysis.py``. Calibration is fitted in an
expanding manner: predictions from earlier walk-forward folds are used to
calibrate later folds. This avoids fitting Platt or isotonic calibration on the
same observations that are later evaluated.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score


PROJECT_ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = PROJECT_ROOT / "docs" / "assets" / "team_order_sensitivity" / "team_order_sensitivity_predictions.csv"
OUTPUT_DIR = PROJECT_ROOT / "docs" / "assets" / "calibration_symmetry_diagnostic"
TARGET = "y_true"
RAW_VARIANTS = ["Original orientation", "Order-symmetrized prediction"]
MIN_CALIBRATION_SAMPLES = 1000
EPSILON = 0.001


def logit(probability: np.ndarray) -> np.ndarray:
    """Calculate clipped logit transformation.

    Args:
        probability: Probability vector.

    Returns:
        Logit-transformed vector as a two-dimensional array.
    """

    clipped = np.clip(probability.astype(float), EPSILON, 1.0 - EPSILON)
    return np.log(clipped / (1.0 - clipped)).reshape(-1, 1)


def calculate_ece(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> float:
    """Calculate Expected Calibration Error."""

    boundaries = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for lower, upper in zip(boundaries[:-1], boundaries[1:]):
        in_bin = (y_prob > lower) & (y_prob <= upper)
        weight = float(np.mean(in_bin))
        if weight > 0.0:
            ece += abs(float(np.mean(y_true[in_bin])) - float(np.mean(y_prob[in_bin]))) * weight
    return ece


def expanding_calibrate_variant(data: pd.DataFrame, variant: str) -> pd.DataFrame:
    """Apply expanding Platt and isotonic calibration to one prediction stream.

    Args:
        data: Prediction frame containing fold, y_true and y_prob.
        variant: Variant name to calibrate.

    Returns:
        Frame with raw and calibrated probabilities.
    """

    variant_data = data[data["variant"] == variant].copy().sort_values(["fold", "date"])
    calibrated_parts: list[pd.DataFrame] = []

    for fold in sorted(variant_data["fold"].unique()):
        test_fold = variant_data[variant_data["fold"] == fold].copy()
        calibration_pool = variant_data[variant_data["fold"] < fold].copy()
        raw_prob = np.clip(test_fold["y_prob"].to_numpy(dtype=float), EPSILON, 1.0 - EPSILON)

        platt_prob = raw_prob.copy()
        isotonic_prob = raw_prob.copy()
        calibrated = False

        if len(calibration_pool) >= MIN_CALIBRATION_SAMPLES and calibration_pool[TARGET].nunique() == 2:
            cal_y = calibration_pool[TARGET].astype(int).to_numpy()
            cal_prob = np.clip(calibration_pool["y_prob"].to_numpy(dtype=float), EPSILON, 1.0 - EPSILON)

            platt = LogisticRegression(C=1.0, solver="lbfgs", max_iter=1000)
            platt.fit(logit(cal_prob), cal_y)
            platt_prob = np.clip(platt.predict_proba(logit(raw_prob))[:, 1], EPSILON, 1.0 - EPSILON)

            isotonic = IsotonicRegression(out_of_bounds="clip", y_min=EPSILON, y_max=1.0 - EPSILON)
            isotonic.fit(cal_prob, cal_y)
            isotonic_prob = np.clip(isotonic.predict(raw_prob), EPSILON, 1.0 - EPSILON)
            calibrated = True

        for calibration_name, probability in [
            ("raw", raw_prob),
            ("platt_expanding", platt_prob),
            ("isotonic_expanding", isotonic_prob),
        ]:
            output = test_fold[["golgg_match_id", "date", "fold", TARGET]].copy()
            output["base_variant"] = variant
            output["calibration"] = calibration_name
            output["y_prob"] = probability
            output["calibrator_available"] = int(calibrated)
            calibrated_parts.append(output)

    return pd.concat(calibrated_parts, ignore_index=True)


def evaluate_predictions(predictions: pd.DataFrame) -> pd.DataFrame:
    """Evaluate raw and calibrated probability streams."""

    rows: list[dict[str, float | int | str]] = []
    for (base_variant, calibration), group in predictions.groupby(["base_variant", "calibration"]):
        y_true = group[TARGET].astype(int).to_numpy()
        y_prob = np.clip(group["y_prob"].to_numpy(dtype=float), EPSILON, 1.0 - EPSILON)
        rows.append(
            {
                "base_variant": base_variant,
                "calibration": calibration,
                "sample_size": len(group),
                "calibrated_sample_rate": float(group["calibrator_available"].mean()),
                "auc": roc_auc_score(y_true, y_prob),
                "logloss": log_loss(y_true, y_prob),
                "brier": brier_score_loss(y_true, y_prob),
                "ece": calculate_ece(y_true, y_prob),
                "accuracy_0_5": accuracy_score(y_true, y_prob >= 0.5),
            }
        )
    return pd.DataFrame(rows).sort_values(["base_variant", "logloss"])


def main() -> None:
    """Run calibration diagnostic."""

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not INPUT_PATH.exists():
        raise FileNotFoundError(
            f"Missing predictions at {INPUT_PATH}. Run 06ag_team_order_sensitivity_analysis.py first."
        )

    predictions = pd.read_csv(INPUT_PATH, parse_dates=["date"])
    calibrated = pd.concat(
        [expanding_calibrate_variant(predictions, variant) for variant in RAW_VARIANTS],
        ignore_index=True,
    )
    metrics = evaluate_predictions(calibrated)

    calibrated.to_csv(OUTPUT_DIR / "calibration_symmetry_predictions.csv", index=False)
    metrics.to_csv(OUTPUT_DIR / "calibration_symmetry_metrics.csv", index=False)

    print("Calibration diagnostic metrics:")
    print(metrics.to_string(index=False, float_format=lambda value: f"{value:.6f}"))
    print(f"\nSaved outputs to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
