"""Evaluate leakage-safe calibration for standard and symmetrized predictions.

The script uses out-of-time walk-forward predictions generated by
``06ag_team_order_sensitivity_analysis.py``. Calibration is fitted in an
expanding manner: predictions from earlier walk-forward folds are used to
calibrate later folds. This avoids fitting Platt or isotonic calibration on the
same observations that are later evaluated.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from src.analysis.probability_metrics import evaluate_probability_groups

from src.models.calibration import expanding_platt_isotonic_calibration

INPUT_PATH = PROJECT_ROOT / "docs" / "assets" / "team_order_sensitivity" / "team_order_sensitivity_predictions.csv"
OUTPUT_DIR = PROJECT_ROOT / "docs" / "assets" / "calibration_symmetry_diagnostic"
TARGET = "y_true"
RAW_VARIANTS = ["Original orientation", "Order-symmetrized prediction"]
MIN_CALIBRATION_SAMPLES = 1000
EPSILON = 0.001


def expanding_calibrate_variant(data: pd.DataFrame, variant: str) -> pd.DataFrame:
    """Apply expanding Platt and isotonic calibration to one prediction stream.

    Args:
        data: Prediction frame containing fold, y_true and y_prob.
        variant: Variant name to calibrate.

    Returns:
        Frame with raw and calibrated probabilities.
    """

    return expanding_platt_isotonic_calibration(
        data,
        variant_value=variant,
        variant_column="variant",
        target_column=TARGET,
        min_calibration_samples=MIN_CALIBRATION_SAMPLES,
        epsilon=EPSILON,
    )


def evaluate_predictions(predictions: pd.DataFrame) -> pd.DataFrame:
    """Evaluate raw and calibrated probability streams."""

    return evaluate_probability_groups(
        predictions,
        ["base_variant", "calibration"],
        target_column=TARGET,
        epsilon=EPSILON,
    ).sort_values(["base_variant", "logloss"])


def main() -> None:
    """Run calibration diagnostic."""

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not INPUT_PATH.exists():
        raise FileNotFoundError(
            f"Missing predictions at {INPUT_PATH}. Run 06ag_team_order_sensitivity_analysis.py first."
        )

    predictions = pd.read_csv(INPUT_PATH, parse_dates=["date"])
    calibrated = pd.concat(
        [expanding_calibrate_variant(predictions, variant) for variant in RAW_VARIANTS],
        ignore_index=True,
    )
    metrics = evaluate_predictions(calibrated)

    calibrated.to_csv(OUTPUT_DIR / "calibration_symmetry_predictions.csv", index=False)
    metrics.to_csv(OUTPUT_DIR / "calibration_symmetry_metrics.csv", index=False)

    print("Calibration diagnostic metrics:")
    print(metrics.to_string(index=False, float_format=lambda value: f"{value:.6f}"))
    print(f"\nSaved outputs to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
