"""Validate Optuna LightGBM parameters with walk-forward evaluation.

This script is a follow-up to ``13_hyperparameter_optimization.py``. Optuna used
a chronological 80/20 holdout, so this script checks whether the selected
hyperparameters still look good under a more operational walk-forward protocol.
The evaluation is restricted to matches present in ``odds.csv``.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ASSETS_DIR = PROJECT_ROOT / "docs" / "assets" / "metamodel_walkforward_optuna"
REPORT_PATH = PROJECT_ROOT / "docs" / "whitepaper" / "06h_walkforward_optuna_autogenerated.md"
TARGET = "y_true"

FEATURES = [
    "player_elo",
    "player_gl",
    "player_ts",
    "player_os",
    "player_pl",
    "player_tm",
    "player_elo_min1",
    "player_elo_min2",
    "player_gl_max1",
    "player_gl_max2",
    "player_gl_rd_avg1",
    "player_gl_rd_avg2",
    "player_ts_sigma_avg1",
    "player_ts_sigma_avg2",
    "player_os_sigma_avg1",
    "player_os_sigma_avg2",
    "player_pl_sigma_avg1",
    "player_pl_sigma_avg2",
    "player_tm_sigma_avg1",
    "player_tm_sigma_avg2",
]


def configure_plot_style() -> None:
    """Configure compact plots for thesis artefacts."""

    sns.set_theme(style="whitegrid", context="talk")
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 300,
            "axes.titleweight": "bold",
            "axes.titlesize": 14,
            "axes.labelsize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )


def calculate_ece(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> float:
    """Calculate Expected Calibration Error.

    Args:
        y_true: Binary labels.
        y_prob: Predicted probabilities.
        n_bins: Number of equal-width probability bins.

    Returns:
        Weighted absolute calibration error.
    """

    boundaries = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for lower, upper in zip(boundaries[:-1], boundaries[1:]):
        in_bin = (y_prob > lower) & (y_prob <= upper)
        prop = float(np.mean(in_bin))
        if prop > 0:
            accuracy = float(np.mean(y_true[in_bin]))
            confidence = float(np.mean(y_prob[in_bin]))
            ece += abs(accuracy - confidence) * prop
    return ece


def default_report_params() -> dict[str, object]:
    """Return LightGBM parameters previously used in metamodel experiments."""

    return {
        "max_depth": 6,
        "num_leaves": 6,
        "learning_rate": 0.024,
        "n_estimators": 486,
        "min_child_samples": 60,
        "subsample": 0.727,
        "colsample_bytree": 0.859,
        "reg_alpha": 0.0,
        "reg_lambda": 0.0,
        "verbosity": -1,
        "random_state": 42,
    }


def optuna_params() -> dict[str, object]:
    """Return best parameters from the current Optuna holdout run.

    The values mirror ``docs/assets/metamodel_best_params_optuna_odds.txt``
    generated by ``13_hyperparameter_optimization.py`` after adapting the data
    pipeline to the current GOL.GG schema.
    """

    return {
        "max_depth": 3,
        "num_leaves": 4,
        "learning_rate": 0.05982187713534574,
        "n_estimators": 172,
        "min_child_samples": 158,
        "subsample": 0.6126838656136981,
        "colsample_bytree": 0.8982359216990613,
        "reg_alpha": 0.23616604142280218,
        "reg_lambda": 5.375206536269943e-05,
        "verbosity": -1,
        "random_state": 42,
    }


def load_odds_sample() -> pd.DataFrame:
    """Load rating predictions restricted to matches mapped in odds.csv.

    Returns:
        Chronologically sorted modelling frame filtered to 2020+ matches.
    """

    predictions = pd.read_csv(PROJECT_ROOT / "data" / "golgg_y_predicts.csv")
    odds = pd.read_csv(PROJECT_ROOT / "data" / "odds.csv", usecols=["golgg_match_id"])
    predictions["golgg_match_id"] = predictions["golgg_match_id"].astype(str)
    odds["golgg_match_id"] = odds["golgg_match_id"].astype(str)
    data = predictions.merge(odds.drop_duplicates(), on="golgg_match_id", how="inner")
    data["date"] = pd.to_datetime(data["date"])
    data = data.dropna(subset=FEATURES + [TARGET]).copy()
    data = data[data["date"] >= pd.Timestamp("2020-01-01")]
    return data.sort_values("date").reset_index(drop=True)


def walk_forward_predict(
    data: pd.DataFrame,
    params: dict[str, object],
    update_interval: int,
    mask_rate: float,
    random_seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, pd.Series]:
    """Generate walk-forward predictions for one model configuration.

    Args:
        data: Chronologically sorted odds-mapped modelling data.
        params: LightGBM parameters.
        update_interval: Number of future matches between model refits.
        mask_rate: Probability of masking each training feature value.
        random_seed: Seed used for deterministic masking.

    Returns:
        Tuple of true labels, predicted probabilities, and prediction dates.
    """

    initial_train = data[data["date"] < pd.Timestamp("2021-01-01")].copy()
    test_pool = data[data["date"] >= pd.Timestamp("2021-01-01")].copy()
    if initial_train.empty or test_pool.empty:
        raise ValueError("Walk-forward split produced empty train or test set.")

    rng = np.random.default_rng(random_seed)
    train_df = initial_train.copy()
    y_true_parts: list[np.ndarray] = []
    prob_parts: list[np.ndarray] = []
    date_parts: list[pd.Series] = []

    for start in tqdm(range(0, len(test_pool), update_interval), desc="Walk-forward"):
        test_chunk = test_pool.iloc[start : start + update_interval]
        x_train = train_df[FEATURES].copy()
        if mask_rate > 0:
            x_train = x_train.mask(rng.random(x_train.shape) < mask_rate)

        model = LGBMClassifier(**params)
        model.fit(x_train, train_df[TARGET].astype(int))
        probabilities = model.predict_proba(test_chunk[FEATURES])[:, 1]

        y_true_parts.append(test_chunk[TARGET].astype(int).to_numpy())
        prob_parts.append(probabilities)
        date_parts.append(test_chunk["date"])
        train_df = pd.concat([train_df, test_chunk], ignore_index=True)

    return np.concatenate(y_true_parts), np.concatenate(prob_parts), pd.concat(date_parts, ignore_index=True)


def evaluate_predictions(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    dates: pd.Series,
    variant: str,
    params_name: str,
    update_interval: int,
    mask_rate: float,
) -> dict[str, object]:
    """Calculate metrics for one walk-forward configuration."""

    clipped = np.clip(y_prob, 0.001, 0.999)
    return {
        "variant": variant,
        "params": params_name,
        "update_interval": update_interval,
        "mask_rate": mask_rate,
        "sample_size": len(y_true),
        "date_min": dates.min().date().isoformat(),
        "date_max": dates.max().date().isoformat(),
        "auc": roc_auc_score(y_true, clipped),
        "logloss": log_loss(y_true, clipped),
        "brier": brier_score_loss(y_true, clipped),
        "ece": calculate_ece(y_true, clipped),
        "accuracy_0_5": accuracy_score(y_true, clipped >= 0.5),
    }


def save_metric_plot(results: pd.DataFrame, metric: str, output_path: Path) -> None:
    """Save compact bar plot for a selected metric."""

    data = results.sort_values(metric, ascending=(metric == "logloss"))
    plt.figure(figsize=(12, 5.5))
    ax = sns.barplot(data=data, x="variant", y=metric, hue="params", palette="mako")
    for container in ax.containers:
        ax.bar_label(container, fmt="%.4f", fontsize=8, padding=3)
    values = data[metric].to_numpy()
    margin = max((values.max() - values.min()) * 0.25, 0.0015)
    ax.set_ylim(values.min() - margin, values.max() + margin)
    ax.set_title(f"Walk-forward Optuna vs default — {metric.upper()}", pad=15)
    ax.set_xlabel("")
    ax.set_ylabel(metric.upper())
    ax.tick_params(axis="x", rotation=20)
    sns.despine()
    plt.tight_layout()
    plt.savefig(output_path, bbox_inches="tight")
    plt.close()


def write_markdown_summary(results: pd.DataFrame) -> None:
    """Write an autogenerated Obsidian-compatible report."""

    lines = [
        "---",
        "type: experiment-report",
        "tags: [whitepaper, metamodel, walk-forward, optuna, odds-sample]",
        "project: inzynierka",
        "date: 2026-04-30",
        "status: autogenerated",
        "---",
        "",
        "# 06h. Walk-forward validation of Optuna parameters",
        "",
        "> [!abstract]",
        "> Ten raport sprawdza, czy parametry LightGBM dobrane przez Optunę na chronologicznym holdoucie utrzymują przewagę w procedurze walk-forward na meczach z `odds.csv`.",
        "",
        results[
            [
                "variant",
                "params",
                "update_interval",
                "mask_rate",
                "sample_size",
                "auc",
                "logloss",
                "brier",
                "ece",
                "accuracy_0_5",
            ]
        ].to_markdown(index=False, floatfmt=".5f"),
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run walk-forward validation and write artefacts."""

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    configure_plot_style()
    data = load_odds_sample()

    experiments = [
        ("Default params, update 1000, no masking", "default", default_report_params(), 1000, 0.0),
        ("Optuna params, update 1000, no masking", "optuna", optuna_params(), 1000, 0.0),
        ("Default params, update 2000, no masking", "default", default_report_params(), 2000, 0.0),
        ("Optuna params, update 2000, no masking", "optuna", optuna_params(), 2000, 0.0),
        ("Optuna params, update 2000, masking 0.1", "optuna", optuna_params(), 2000, 0.1),
    ]

    rows: list[dict[str, object]] = []
    for variant, params_name, params, update_interval, mask_rate in experiments:
        y_true, y_prob, dates = walk_forward_predict(data, params, update_interval, mask_rate)
        rows.append(
            evaluate_predictions(
                y_true,
                y_prob,
                dates,
                variant,
                params_name,
                update_interval,
                mask_rate,
            )
        )

    results = pd.DataFrame(rows).sort_values("logloss").reset_index(drop=True)
    results.to_csv(ASSETS_DIR / "walkforward_optuna_results.csv", index=False)
    save_metric_plot(results, "logloss", ASSETS_DIR / "walkforward_optuna_logloss.png")
    save_metric_plot(results, "auc", ASSETS_DIR / "walkforward_optuna_auc.png")
    write_markdown_summary(results)

    print("\n=== WALK-FORWARD OPTUNA VALIDATION ===")
    print(results.to_string(index=False))
    print("\nSaved artefacts to:", ASSETS_DIR)


if __name__ == "__main__":
    main()
