"""Search combined best metamodel settings with walk-forward validation.

This script combines the best candidates discovered in previous experiments:

* optimized TrueSkill/OpenSkill predictions already present in ``golgg_y_predicts.csv``;
* Optuna LightGBM parameters from ``13_hyperparameter_optimization.py``;
* player-only feature preference;
* context window 50 as the best rolling-context candidate;
* update intervals 1000 and 2000;
* no masking versus light masking 0.1.

All evaluation rows are restricted to matches present in ``odds.csv``. Rolling
context is computed chronologically from full ``golgg_matches.json`` history.
"""

from __future__ import annotations

import json
from collections import deque
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, brier_score_loss, log_loss, roc_auc_score
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ASSETS_DIR = PROJECT_ROOT / "docs" / "assets" / "metamodel_best_config_point6"
REPORT_PATH = PROJECT_ROOT / "docs" / "whitepaper" / "06i_best_metamodel_config_autogenerated.md"
TARGET = "y_true"
CONTEXT_WINDOW = 50

OPTUNA_BASE_FEATURES = [
    "player_elo",
    "player_gl",
    "player_ts",
    "player_os",
    "player_pl",
    "player_tm",
    "player_elo_min1",
    "player_elo_min2",
    "player_gl_max1",
    "player_gl_max2",
    "player_gl_rd_avg1",
    "player_gl_rd_avg2",
    "player_ts_sigma_avg1",
    "player_ts_sigma_avg2",
    "player_os_sigma_avg1",
    "player_os_sigma_avg2",
    "player_pl_sigma_avg1",
    "player_pl_sigma_avg2",
    "player_tm_sigma_avg1",
    "player_tm_sigma_avg2",
]

ROLLING_CORE_FEATURES = [
    "t1_rolling_win_rate",
    "t2_rolling_win_rate",
    "t1_rolling_gd15",
    "t2_rolling_gd15",
]

ROLLING_FULL_FEATURES = [
    "t1_rolling_win_rate",
    "t2_rolling_win_rate",
    "t1_rolling_kills",
    "t2_rolling_kills",
    "t1_rolling_deaths",
    "t2_rolling_deaths",
    "t1_rolling_gd15",
    "t2_rolling_gd15",
    "t1_rolling_dpm",
    "t2_rolling_dpm",
    "t1_rolling_vspm",
    "t2_rolling_vspm",
]


def configure_plot_style() -> None:
    """Configure compact, thesis-friendly plot style."""

    sns.set_theme(style="whitegrid", context="talk")
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 300,
            "axes.titleweight": "bold",
            "axes.titlesize": 14,
            "axes.labelsize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )


def calculate_ece(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> float:
    """Calculate Expected Calibration Error.

    Args:
        y_true: Binary labels.
        y_prob: Predicted positive-class probabilities.
        n_bins: Number of probability bins.

    Returns:
        Weighted average calibration error.
    """

    boundaries = np.linspace(0.0, 1.0, n_bins + 1)
    ece = 0.0
    for lower, upper in zip(boundaries[:-1], boundaries[1:]):
        in_bin = (y_prob > lower) & (y_prob <= upper)
        prop = float(np.mean(in_bin))
        if prop > 0:
            accuracy = float(np.mean(y_true[in_bin]))
            confidence = float(np.mean(y_prob[in_bin]))
            ece += abs(accuracy - confidence) * prop
    return ece


def optuna_params() -> dict[str, object]:
    """Return corrected Optuna LightGBM parameters."""

    return {
        "max_depth": 2,
        "num_leaves": 3,
        "learning_rate": 0.0495484856620236,
        "n_estimators": 415,
        "min_child_samples": 65,
        "subsample": 0.6423308984276832,
        "colsample_bytree": 0.8371970895768155,
        "reg_alpha": 0.0026379865214127248,
        "reg_lambda": 4.578052284019224e-08,
        "verbosity": -1,
        "random_state": 42,
    }


def default_team_stats() -> dict[str, float]:
    """Return neutral defaults for teams without historical context."""

    return {
        "win_rate": 0.5,
        "kills": 12.0,
        "deaths": 12.0,
        "gd15": 0.0,
        "dpm": 1800.0,
        "vspm": 7.0,
    }


def safe_stat(player: dict[str, Any], key: str) -> float:
    """Read a numeric player statistic with zero fallback."""

    value = player.get("stats", {}).get(key, 0.0)
    return float(value or 0.0)


def average_history(history: deque[dict[str, float]] | None) -> dict[str, float]:
    """Average a team's rolling game history."""

    if not history:
        return default_team_stats()
    rows = list(history)
    return {
        "win_rate": float(np.mean([row["win"] for row in rows])),
        "kills": float(np.mean([row["kills"] for row in rows])),
        "deaths": float(np.mean([row["deaths"] for row in rows])),
        "gd15": float(np.mean([row["gd15"] for row in rows])),
        "dpm": float(np.mean([row["dpm"] for row in rows])),
        "vspm": float(np.mean([row["vspm"] for row in rows])),
    }


def update_team_history(
    team_history: dict[str, deque[dict[str, float]]],
    team_id: str,
    game: dict[str, Any],
    window_size: int,
) -> None:
    """Update rolling history for one team after a completed game."""

    is_team_1 = str(game.get("t1_id")) == str(team_id)
    win = bool(game.get("t1_win")) if is_team_1 else bool(game.get("t2_win"))
    players_key = "t1_players" if is_team_1 else "t2_players"
    players = game.get(players_key, {}) or {}
    game_stats = {
        "win": float(win),
        "kills": sum(safe_stat(player, "kills") for player in players.values()),
        "deaths": sum(safe_stat(player, "deaths") for player in players.values()),
        "dpm": sum(safe_stat(player, "dpm") for player in players.values()),
        "vspm": sum(safe_stat(player, "vspm") for player in players.values()),
        "gd15": sum(safe_stat(player, "gd@15") for player in players.values()),
    }
    if team_id not in team_history:
        team_history[team_id] = deque(maxlen=window_size)
    team_history[team_id].append(game_stats)


def generate_rolling_features(window_size: int) -> pd.DataFrame:
    """Generate leakage-safe rolling context features.

    Args:
        window_size: Number of historical games retained per team.

    Returns:
        Match-level rolling context frame.
    """

    with open(PROJECT_ROOT / "data" / "golgg_matches.json", "r", encoding="utf-8") as file:
        matches = json.load(file)
    matches.sort(key=lambda item: item["date"])

    team_history: dict[str, deque[dict[str, float]]] = {}
    rows: list[dict[str, object]] = []
    for match in tqdm(matches, desc=f"Rolling window {window_size}"):
        match_id = str(match["match_id"])
        team_1 = str(match["tid_1"])
        team_2 = str(match["tid_2"])
        t1_stats = average_history(team_history.get(team_1))
        t2_stats = average_history(team_history.get(team_2))
        row: dict[str, object] = {"golgg_match_id": match_id, "context_window": window_size}
        for stat, value in t1_stats.items():
            row[f"t1_rolling_{stat}"] = value
        for stat, value in t2_stats.items():
            row[f"t2_rolling_{stat}"] = value
        rows.append(row)

        for game in match.get("games", []) or []:
            update_team_history(team_history, team_1, game, window_size)
            update_team_history(team_history, team_2, game, window_size)

    return pd.DataFrame(rows)


def load_base_data() -> pd.DataFrame:
    """Load rating predictions restricted to odds-mapped matches."""

    predictions = pd.read_csv(PROJECT_ROOT / "data" / "golgg_y_predicts.csv")
    odds = pd.read_csv(PROJECT_ROOT / "data" / "odds.csv", usecols=["golgg_match_id"])
    predictions["golgg_match_id"] = predictions["golgg_match_id"].astype(str)
    odds["golgg_match_id"] = odds["golgg_match_id"].astype(str)
    data = predictions.merge(odds.drop_duplicates(), on="golgg_match_id", how="inner")
    data["date"] = pd.to_datetime(data["date"])
    data = data[data["date"] >= pd.Timestamp("2020-01-01")].copy()
    return data.sort_values("date").reset_index(drop=True)


def walk_forward_predict(
    data: pd.DataFrame,
    features: list[str],
    update_interval: int,
    mask_rate: float,
    random_seed: int = 42,
) -> tuple[np.ndarray, np.ndarray, pd.Series]:
    """Run walk-forward prediction for one combined configuration."""

    clean = data.dropna(subset=features + [TARGET]).copy().sort_values("date").reset_index(drop=True)
    initial_train = clean[clean["date"] < pd.Timestamp("2021-01-01")].copy()
    test_pool = clean[clean["date"] >= pd.Timestamp("2021-01-01")].copy()
    if initial_train.empty or test_pool.empty:
        raise ValueError("Walk-forward split produced empty train or test set.")

    rng = np.random.default_rng(random_seed)
    train_df = initial_train.copy()
    y_true_parts: list[np.ndarray] = []
    prob_parts: list[np.ndarray] = []
    date_parts: list[pd.Series] = []
    params = optuna_params()

    for start in tqdm(range(0, len(test_pool), update_interval), desc="Walk-forward"):
        test_chunk = test_pool.iloc[start : start + update_interval]
        x_train = train_df[features].copy()
        if mask_rate > 0:
            x_train = x_train.mask(rng.random(x_train.shape) < mask_rate)

        model = LGBMClassifier(**params)
        model.fit(x_train, train_df[TARGET].astype(int))
        probabilities = model.predict_proba(test_chunk[features])[:, 1]
        y_true_parts.append(test_chunk[TARGET].astype(int).to_numpy())
        prob_parts.append(probabilities)
        date_parts.append(test_chunk["date"])
        train_df = pd.concat([train_df, test_chunk], ignore_index=True)

    return np.concatenate(y_true_parts), np.concatenate(prob_parts), pd.concat(date_parts, ignore_index=True)


def evaluate(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    dates: pd.Series,
    variant: str,
    feature_set: str,
    update_interval: int,
    mask_rate: float,
    n_features: int,
) -> dict[str, object]:
    """Evaluate one prediction vector."""

    clipped = np.clip(y_prob, 0.001, 0.999)
    return {
        "variant": variant,
        "feature_set": feature_set,
        "update_interval": update_interval,
        "mask_rate": mask_rate,
        "n_features": n_features,
        "sample_size": len(y_true),
        "date_min": dates.min().date().isoformat(),
        "date_max": dates.max().date().isoformat(),
        "auc": roc_auc_score(y_true, clipped),
        "logloss": log_loss(y_true, clipped),
        "brier": brier_score_loss(y_true, clipped),
        "ece": calculate_ece(y_true, clipped),
        "accuracy_0_5": accuracy_score(y_true, clipped >= 0.5),
    }


def save_plot(results: pd.DataFrame, metric: str, output_path: Path) -> None:
    """Save a compact ranking plot for tested configurations."""

    data = results.sort_values(metric, ascending=(metric == "logloss"))
    plt.figure(figsize=(13, 6))
    ax = sns.barplot(data=data, x="variant", y=metric, hue="feature_set", palette="mako")
    for container in ax.containers:
        ax.bar_label(container, fmt="%.4f", fontsize=7, padding=3)
    values = data[metric].to_numpy()
    margin = max((values.max() - values.min()) * 0.25, 0.0015)
    ax.set_ylim(values.min() - margin, values.max() + margin)
    ax.set_title(f"Best combined metamodel settings — {metric.upper()}", pad=15)
    ax.set_xlabel("")
    ax.set_ylabel(metric.upper())
    ax.tick_params(axis="x", rotation=30)
    sns.despine()
    plt.tight_layout()
    plt.savefig(output_path, bbox_inches="tight")
    plt.close()


def write_markdown_summary(results: pd.DataFrame) -> None:
    """Write autogenerated Markdown summary."""

    cols = [
        "variant",
        "feature_set",
        "update_interval",
        "mask_rate",
        "n_features",
        "sample_size",
        "auc",
        "logloss",
        "brier",
        "ece",
        "accuracy_0_5",
    ]
    lines = [
        "---",
        "type: experiment-report",
        "tags: [whitepaper, metamodel, best-config, walk-forward, odds-sample]",
        "project: inzynierka",
        "date: 2026-04-30",
        "status: autogenerated",
        "---",
        "",
        "# 06i. Best combined metamodel configuration search",
        "",
        "> [!abstract]",
        "> Eksperyment łączy najlepsze dotychczasowe decyzje: zoptymalizowane ratingi, parametry Optuny, player-only, context window 50, update 1000/2000 i masking 0/0.1.",
        "",
        results[cols].to_markdown(index=False, floatfmt=".5f"),
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run combined best-configuration search."""

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    configure_plot_style()
    base = load_base_data()
    rolling = generate_rolling_features(CONTEXT_WINDOW)
    data = base.merge(rolling, on="golgg_match_id", how="inner").sort_values("date")

    feature_sets = {
        "optuna_player_uncertainty": OPTUNA_BASE_FEATURES,
        "optuna_player_core_context_w50": OPTUNA_BASE_FEATURES + ROLLING_CORE_FEATURES,
        "optuna_player_full_context_w50": OPTUNA_BASE_FEATURES + ROLLING_FULL_FEATURES,
    }
    update_intervals = [1000, 2000]
    mask_rates = [0.0, 0.1]

    rows: list[dict[str, object]] = []
    for feature_name, features in feature_sets.items():
        for update_interval in update_intervals:
            for mask_rate in mask_rates:
                variant = f"{feature_name} | upd={update_interval} | mask={mask_rate}"
                y_true, y_prob, dates = walk_forward_predict(data, features, update_interval, mask_rate)
                rows.append(
                    evaluate(
                        y_true,
                        y_prob,
                        dates,
                        variant,
                        feature_name,
                        update_interval,
                        mask_rate,
                        len(features),
                    )
                )

    results = pd.DataFrame(rows).sort_values("logloss").reset_index(drop=True)
    results.to_csv(ASSETS_DIR / "best_metamodel_config_results.csv", index=False)
    save_plot(results, "logloss", ASSETS_DIR / "best_metamodel_config_logloss.png")
    save_plot(results, "auc", ASSETS_DIR / "best_metamodel_config_auc.png")
    write_markdown_summary(results)

    print("\n=== BEST COMBINED METAMODEL SETTINGS ===")
    print(results.to_string(index=False))
    print("\nSaved artefacts to:", ASSETS_DIR)


if __name__ == "__main__":
    main()
