"""Create the final thesis comparison with logistic regression as main model.

The script reuses already generated walk-forward predictions from the
logistic-regression robustness experiment and aligns them with the final
model-vs-market common sample. It intentionally stays within the thesis scope:
probabilistic match prediction versus bookmaker benchmarks, without betting
execution, expected value, staking, bankroll, or ROI simulation.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from src.analysis.probability_metrics import calculate_ece
SOURCE_COMPARISON_DIR = PROJECT_ROOT / "docs" / "assets" / "final_model_market_comparison"
LOGISTIC_DIR = PROJECT_ROOT / "docs" / "assets" / "logistic_regression_robustness"
OUTPUT_DIR = PROJECT_ROOT / "docs" / "assets" / "final_logistic_market_comparison"
TARGET = "y_true"

MAIN_LOGISTIC_VARIANT = "player_full_context_w50 | L1 | C=0.3"
PLAYER_ONLY_VARIANT = "player_only | L2 | C=0.3"
CORE_CONTEXT_VARIANT = "player_core_context_w50 | L2 | C=1"



def evaluate_probability(data: pd.DataFrame, model: str, column: str) -> dict[str, object]:
    """Evaluate one probability column on the common sample.

    Args:
        data: DataFrame containing target and probability columns.
        model: Human-readable model name.
        column: Probability column to evaluate.

    Returns:
        Dictionary with thesis metrics.
    """

    subset = data[[TARGET, column]].dropna().copy()
    y_true = subset[TARGET].astype(int).to_numpy()
    y_prob = np.clip(subset[column].to_numpy(), 0.001, 0.999)
    return {
        "model": model,
        "probability_column": column,
        "sample_size": int(len(subset)),
        "auc": float(roc_auc_score(y_true, y_prob)),
        "logloss": float(log_loss(y_true, y_prob)),
        "brier": float(brier_score_loss(y_true, y_prob)),
        "ece": calculate_ece(y_true, y_prob),
    }


def load_logistic_variant(predictions: pd.DataFrame, variant: str, column: str) -> pd.DataFrame:
    """Extract one logistic-regression variant from the robustness predictions.

    Args:
        predictions: Long prediction table generated by EXP-014.
        variant: Variant label to select.
        column: Name assigned to the probability column in the output.

    Returns:
        Two-column frame with match ID and selected probability.
    """

    selected = predictions.loc[predictions["variant"] == variant, ["golgg_match_id", "y_prob"]].copy()
    selected["golgg_match_id"] = selected["golgg_match_id"].astype(str)
    return selected.rename(columns={"y_prob": column})


def plot_metric(metrics: pd.DataFrame, metric: str, file_name: str, ylabel: str) -> None:
    """Create a horizontal bar chart for one metric.

    Args:
        metrics: Metrics table sorted in thesis order.
        metric: Metric column to plot.
        file_name: Output PNG file name.
        ylabel: Axis label.
    """

    plot_data = metrics.copy()
    colors = ["#4F6D7A", "#7A8F6F", "#A68A64", "#8E6C88", "#6B7A8F", "#B07D62"]
    fig, ax = plt.subplots(figsize=(11, 6.2))
    bars = ax.bar(plot_data["model"], plot_data[metric], color=colors[: len(plot_data)], edgecolor="white")
    ax.set_ylabel(ylabel, fontsize=13)
    ax.set_title(f"Końcowe porównanie według {metric.upper()}", fontsize=16, pad=14)
    ax.tick_params(axis="x", labelrotation=25, labelsize=10)
    for label in ax.get_xticklabels():
        label.set_horizontalalignment("right")
        label.set_rotation_mode("anchor")
    ax.tick_params(axis="y", labelsize=11)
    values = plot_data[metric].to_numpy()
    margin = max((values.max() - values.min()) * 0.35, 0.002)
    if metric in {"auc"}:
        ax.set_ylim(values.min() - margin, values.max() + margin)
    elif metric in {"ece"}:
        ax.set_ylim(0.0, values.max() * 1.25)
    else:
        ax.set_ylim(values.min() - margin, values.max() + margin)

    for bar, value in zip(bars, values):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value + (ax.get_ylim()[1] - ax.get_ylim()[0]) * 0.015,
            f"{value:.4f}",
            ha="center",
            va="bottom",
            fontsize=10,
        )
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / file_name, dpi=180)
    plt.close(fig)


def main() -> None:
    """Build final logistic-regression-versus-market thesis artefacts."""

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    common = pd.read_csv(SOURCE_COMPARISON_DIR / "final_model_market_common_sample.csv")
    common["golgg_match_id"] = common["golgg_match_id"].astype(str)

    logistic_predictions = pd.read_csv(LOGISTIC_DIR / "logistic_regression_robustness_predictions.csv")
    logistic_predictions["golgg_match_id"] = logistic_predictions["golgg_match_id"].astype(str)

    for variant, column in [
        (MAIN_LOGISTIC_VARIANT, "prob_logistic_full_context_w50"),
        (PLAYER_ONLY_VARIANT, "prob_logistic_player_only"),
        (CORE_CONTEXT_VARIANT, "prob_logistic_core_context_w50"),
    ]:
        common = common.merge(load_logistic_variant(logistic_predictions, variant, column), on="golgg_match_id", how="inner")

    metrics = pd.DataFrame(
        [
            evaluate_probability(common, "LR-W50", "prob_logistic_full_context_w50"),
            evaluate_probability(common, "LR-Player", "prob_logistic_player_only"),
            evaluate_probability(common, "LR-Core", "prob_logistic_core_context_w50"),
            evaluate_probability(common, "LGBM-W50", "prob_full_context_metamodel"),
            evaluate_probability(common, "Player Glicko-2", "player_glicko2"),
            evaluate_probability(common, "Mkt Close", "market_close"),
            evaluate_probability(common, "Mkt Open", "market_open"),
        ]
    ).sort_values("logloss")

    common.to_csv(OUTPUT_DIR / "final_logistic_market_common_sample.csv", index=False)
    metrics.to_csv(OUTPUT_DIR / "final_logistic_market_metrics.csv", index=False)

    plot_metric(metrics, "logloss", "final_logistic_market_logloss.png", "LogLoss (niżej = lepiej)")
    plot_metric(metrics, "auc", "final_logistic_market_auc.png", "AUC (wyżej = lepiej)")
    plot_metric(metrics, "ece", "final_logistic_market_ece.png", "ECE (niżej = lepiej)")

    print("\n=== FINAL LOGISTIC MODEL VS MARKET COMPARISON ===")
    print("Common sample size:", len(common))
    print(metrics.to_string(index=False))
    print("\nSaved artefacts to:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
