"""Create final thesis comparison with two-stage metamodel as main model.

The thesis-level model is the two-stage ranking-context architecture. Stage 1
aggregates ranking probabilities and uncertainty signals. Stage 2 combines the
Stage-1 output with W50 historical context. This script aligns already generated
two-stage walk-forward predictions with bookmaker benchmarks and selected model
controls on the same common sample.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from src.analysis.probability_metrics import calculate_ece, binary_log_loss_vector as log_loss_vector
SOURCE_COMPARISON_DIR = PROJECT_ROOT / "docs" / "assets" / "final_model_market_comparison"
TWO_STAGE_DIR = PROJECT_ROOT / "docs" / "assets" / "two_stage_ranking_context"
OUTPUT_DIR = PROJECT_ROOT / "docs" / "assets" / "final_two_stage_market_comparison"
TARGET = "y_true"
N_BOOTSTRAPS = 10000
RANDOM_SEED = 42

TWO_STAGE_VARIANTS = {
    "TwoStage": "TwoStage rank+unc L1 + W50 L1",
    "TwoStage-Level": "TwoStage rank+unc+level L1 + W50 L1",
    "G2 + context": "G2 + context",
    "LR-W50": "LR-W50",
}



def evaluate_probability(data: pd.DataFrame, model: str, column: str) -> dict[str, object]:
    """Evaluate one probability column on the common sample.

    Args:
        data: DataFrame containing target and probability columns.
        model: Human-readable model name.
        column: Probability column to evaluate.

    Returns:
        Dictionary with thesis metrics.
    """
    subset = data[[TARGET, column]].dropna().copy()
    y_true = subset[TARGET].astype(int).to_numpy()
    y_prob = np.clip(subset[column].to_numpy(), 0.001, 0.999)
    return {
        "model": model,
        "probability_column": column,
        "sample_size": int(len(subset)),
        "auc": float(roc_auc_score(y_true, y_prob)),
        "logloss": float(log_loss(y_true, y_prob)),
        "brier": float(brier_score_loss(y_true, y_prob)),
        "ece": calculate_ece(y_true, y_prob),
    }


def load_variant(predictions: pd.DataFrame, variant: str, column: str) -> pd.DataFrame:
    """Extract one two-stage variant from long prediction output.

    Args:
        predictions: Long prediction table generated by EXP-023/024.
        variant: Variant label to select.
        column: Output probability column name.

    Returns:
        Match ID and selected probability column.
    """
    selected = predictions.loc[predictions["variant"] == variant, ["golgg_match_id", "y_prob"]].copy()
    selected["golgg_match_id"] = selected["golgg_match_id"].astype(str)
    return selected.rename(columns={"y_prob": column})


def plot_metric(metrics: pd.DataFrame, metric: str, file_name: str, ylabel: str) -> None:
    """Create bar plot for one final metric.

    Args:
        metrics: Metrics table.
        metric: Metric column to plot.
        file_name: Output PNG file name.
        ylabel: Axis label.
    """
    plot_data = metrics.copy()
    colors = ["#4F6D7A", "#7A8F6F", "#A68A64", "#8E6C88", "#6B7A8F", "#B07D62", "#9A8C98"]
    fig, ax = plt.subplots(figsize=(11, 6.2))
    bars = ax.bar(plot_data["model"], plot_data[metric], color=colors[: len(plot_data)], edgecolor="white")
    ax.set_ylabel(ylabel, fontsize=13)
    ax.set_title(f"Końcowe porównanie według {metric.upper()}", fontsize=16, pad=14)
    ax.tick_params(axis="x", labelrotation=25, labelsize=10)
    for label in ax.get_xticklabels():
        label.set_horizontalalignment("right")
        label.set_rotation_mode("anchor")
    values = plot_data[metric].to_numpy()
    margin = max((values.max() - values.min()) * 0.35, 0.002)
    if metric == "ece":
        ax.set_ylim(0.0, values.max() * 1.25)
    else:
        ax.set_ylim(values.min() - margin, values.max() + margin)
    for bar, value in zip(bars, values):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value + (ax.get_ylim()[1] - ax.get_ylim()[0]) * 0.015,
            f"{value:.4f}",
            ha="center",
            va="bottom",
            fontsize=10,
        )
    ax.grid(axis="y", linestyle="--", alpha=0.25)
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / file_name, dpi=180)
    plt.close(fig)



def monthly_block_bootstrap(data: pd.DataFrame, main_column: str) -> pd.DataFrame:
    """Compare the main two-stage model with monthly block bootstrap.

    Positive differences mean that the two-stage model has lower LogLoss than
    the benchmark.

    Args:
        data: Common sample with target, dates and probability columns.
        main_column: Probability column for the main two-stage model.

    Returns:
        Bootstrap summary table.
    """
    comparisons = {
        "Mkt Open": "market_open",
        "Mkt Close": "market_close",
        "Player Glicko-2": "player_glicko2",
        "LGBM-W50": "prob_full_context_metamodel",
        "LR-W50": "prob_lr_w50",
        "G2 + context": "prob_g2_plus_context",
    }
    working = data.copy()
    working["month"] = pd.to_datetime(working["date"]).dt.to_period("M").astype(str)
    months = sorted(working["month"].unique())
    y_true = working[TARGET].astype(int).to_numpy()
    main_loss = log_loss_vector(y_true, working[main_column].to_numpy())
    rng = np.random.default_rng(RANDOM_SEED)
    rows: list[dict[str, object]] = []
    for label, column in comparisons.items():
        benchmark_loss = log_loss_vector(y_true, working[column].to_numpy())
        working["delta"] = benchmark_loss - main_loss
        observed = float(working["delta"].mean())
        month_stats = working.groupby("month")["delta"].agg(delta_sum="sum", n="size").loc[months]
        delta_sums = month_stats["delta_sum"].to_numpy(dtype=float)
        counts = month_stats["n"].to_numpy(dtype=float)
        samples = np.empty(N_BOOTSTRAPS, dtype=float)
        for idx in range(N_BOOTSTRAPS):
            sampled_idx = rng.integers(0, len(months), size=len(months))
            samples[idx] = delta_sums[sampled_idx].sum() / counts[sampled_idx].sum()
        rows.append(
            {
                "comparison": f"TwoStage vs {label}",
                "observed_delta_logloss": observed,
                "ci_lower_95": float(np.quantile(samples, 0.025)),
                "ci_upper_95": float(np.quantile(samples, 0.975)),
                "p_one_sided_two_stage_better": float((np.sum(samples <= 0.0) + 1) / (len(samples) + 1)),
                "significantly_better": bool(np.quantile(samples, 0.025) > 0.0),
            }
        )
    return pd.DataFrame(rows).sort_values("observed_delta_logloss", ascending=False)


def plot_bootstrap(bootstrap: pd.DataFrame) -> None:
    """Save confidence-interval plot for final two-stage comparisons."""
    plot_data = bootstrap.sort_values("observed_delta_logloss").copy()
    fig, ax = plt.subplots(figsize=(10.8, 5.8))
    y_positions = np.arange(len(plot_data))
    ax.errorbar(
        plot_data["observed_delta_logloss"],
        y_positions,
        xerr=[
            plot_data["observed_delta_logloss"] - plot_data["ci_lower_95"],
            plot_data["ci_upper_95"] - plot_data["observed_delta_logloss"],
        ],
        fmt="o",
        color="#4F6D7A",
        ecolor="#A68A64",
        capsize=4,
    )
    ax.axvline(0.0, color="#333333", linestyle="--", linewidth=1)
    ax.set_yticks(y_positions)
    ax.set_yticklabels(plot_data["comparison"])
    ax.set_xlabel("Różnica LogLoss względem TwoStage")
    ax.set_title("Monthly block bootstrap — TwoStage vs benchmarki")
    ax.grid(axis="x", linestyle="--", alpha=0.25)
    fig.tight_layout()
    fig.savefig(OUTPUT_DIR / "final_two_stage_market_bootstrap_ci.png", dpi=180)
    plt.close(fig)


def main() -> None:
    """Build final two-stage-versus-market thesis artefacts."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    common = pd.read_csv(SOURCE_COMPARISON_DIR / "final_model_market_common_sample.csv")
    common["golgg_match_id"] = common["golgg_match_id"].astype(str)

    two_stage = pd.read_csv(TWO_STAGE_DIR / "two_stage_predictions.csv")
    two_stage["golgg_match_id"] = two_stage["golgg_match_id"].astype(str)

    for short_name, variant_name in TWO_STAGE_VARIANTS.items():
        column = "prob_" + short_name.lower().replace(" ", "_").replace("+", "plus").replace("-", "_")
        common = common.merge(load_variant(two_stage, variant_name, column), on="golgg_match_id", how="inner")

    metrics = pd.DataFrame(
        [
            evaluate_probability(common, "TwoStage", "prob_twostage"),
            evaluate_probability(common, "TwoStage-Level", "prob_twostage_level"),
            evaluate_probability(common, "LR-W50", "prob_lr_w50"),
            evaluate_probability(common, "G2 + context", "prob_g2_plus_context"),
            evaluate_probability(common, "LGBM-W50", "prob_full_context_metamodel"),
            evaluate_probability(common, "Player Glicko-2", "player_glicko2"),
            evaluate_probability(common, "Mkt Close", "market_close"),
            evaluate_probability(common, "Mkt Open", "market_open"),
        ]
    ).sort_values("logloss")
    bootstrap = monthly_block_bootstrap(common, "prob_twostage")

    common.to_csv(OUTPUT_DIR / "final_two_stage_market_common_sample.csv", index=False)
    metrics.to_csv(OUTPUT_DIR / "final_two_stage_market_metrics.csv", index=False)
    bootstrap.to_csv(OUTPUT_DIR / "final_two_stage_market_bootstrap.csv", index=False)

    plot_metric(metrics, "logloss", "final_two_stage_market_logloss.png", "LogLoss (niżej = lepiej)")
    plot_metric(metrics, "auc", "final_two_stage_market_auc.png", "AUC (wyżej = lepiej)")
    plot_metric(metrics, "ece", "final_two_stage_market_ece.png", "ECE (niżej = lepiej)")
    plot_bootstrap(bootstrap)

    print("\n=== FINAL TWO-STAGE MODEL VS MARKET COMPARISON ===")
    print("Common sample size:", len(common))
    print(metrics.to_string(index=False))
    print("\n=== MONTHLY BLOCK BOOTSTRAP VS TWOSTAGE ===")
    print(bootstrap.to_string(index=False))
    print("\nSaved artefacts to:", OUTPUT_DIR)


if __name__ == "__main__":
    main()
