"""Shared plotting style for thesis figures.

The thesis mixes figures generated by several independent experiment scripts.
This module centralizes typography, grid settings and a muted pastel palette so
that regenerated plots remain visually consistent across EDA, ranking and model
evaluation chapters.
"""

from __future__ import annotations

from collections.abc import Sequence

import matplotlib.pyplot as plt
import seaborn as sns


PASTEL_BLUE = "#6B8FB3"
PASTEL_ORANGE = "#D9A066"
PASTEL_GREEN = "#7FA883"
PASTEL_RED = "#C97C7C"
PASTEL_PURPLE = "#A48CBF"
PASTEL_BROWN = "#B69B7D"
PASTEL_TEAL = "#72A6A6"
PASTEL_GRAY = "#9AA3A8"
DARK_TEXT = "#2F3640"
GRID_COLOR = "#D8DEE6"

PASTEL_PALETTE: list[str] = [
    PASTEL_BLUE,
    PASTEL_ORANGE,
    PASTEL_GREEN,
    PASTEL_RED,
    PASTEL_PURPLE,
    PASTEL_BROWN,
    PASTEL_TEAL,
    PASTEL_GRAY,
]

MARKET_PALETTE: dict[str, str] = {
    "Market Open": PASTEL_BLUE,
    "Mkt Open": PASTEL_BLUE,
    "Market Close": PASTEL_ORANGE,
    "Mkt Close": PASTEL_ORANGE,
}

MODEL_PALETTE: dict[str, str] = {
    "LR-ElasticNet-W20-Binomial": PASTEL_BLUE,
    "Logistic Regression ElasticNet W20-Binomial": PASTEL_BLUE,
    "ExtraTrees-W20-Binomial": PASTEL_ORANGE,
    "ExtraTrees W20-Binomial": PASTEL_ORANGE,
    "LightGBM-W20-Binomial": PASTEL_GREEN,
    "LightGBM W20-Binomial": PASTEL_GREEN,
    "HGB-W20-Binomial": PASTEL_RED,
    "HistGradientBoosting W20-Binomial": PASTEL_RED,
    "MLP-W20-Binomial": PASTEL_PURPLE,
    "MLP W20-Binomial": PASTEL_PURPLE,
    "Player Glicko-2": PASTEL_GREEN,
}


def apply_thesis_style(context: str = "paper") -> None:
    """Apply the shared visual style for thesis plots.

    Args:
        context: Seaborn context name. Use ``"paper"`` for most thesis figures
            and ``"talk"`` only for large standalone report images.
    """

    sns.set_theme(
        style="whitegrid",
        context=context,
        palette=PASTEL_PALETTE,
        rc={
            "figure.facecolor": "white",
            "savefig.facecolor": "white",
            "axes.facecolor": "white",
            "axes.edgecolor": "#C9D1D9",
            "axes.labelcolor": DARK_TEXT,
            "axes.titlecolor": DARK_TEXT,
            "axes.titleweight": "bold",
            "axes.titlesize": 14,
            "axes.labelsize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.fontsize": 9,
            "legend.title_fontsize": 9,
            "grid.color": GRID_COLOR,
            "grid.linestyle": "--",
            "grid.alpha": 0.55,
        },
    )
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "font.family": "DejaVu Sans",
        }
    )


def palette(n_colors: int | None = None) -> list[str]:
    """Return the shared pastel palette.

    Args:
        n_colors: Optional number of colors to return.

    Returns:
        List of hex color codes.
    """

    if n_colors is None:
        return PASTEL_PALETTE.copy()
    return [PASTEL_PALETTE[index % len(PASTEL_PALETTE)] for index in range(n_colors)]


def colors_for(labels: Sequence[str], fallback: Sequence[str] | None = None) -> list[str]:
    """Map model/benchmark labels to consistent thesis colors.

    Args:
        labels: Labels used in a plot.
        fallback: Optional fallback palette. If omitted, the thesis palette is
            cycled.

    Returns:
        Color for each label.
    """

    fallback_palette = list(fallback or PASTEL_PALETTE)
    colors: list[str] = []
    for index, label in enumerate(labels):
        colors.append(
            MODEL_PALETTE.get(
                label,
                MARKET_PALETTE.get(label, fallback_palette[index % len(fallback_palette)]),
            )
        )
    return colors


def clean_axis(ax: plt.Axes, grid_axis: str = "y") -> None:
    """Apply consistent final touches to a Matplotlib axis.

    Args:
        ax: Axis to clean.
        grid_axis: Axis on which the grid should be visible.
    """

    ax.grid(axis=grid_axis, linestyle="--", alpha=0.45, color=GRID_COLOR)
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines["left"].set_color("#C9D1D9")
    ax.spines["bottom"].set_color("#C9D1D9")
