"""Segment calibration and block bootstrap diagnostics for the whitepaper.

The script extends the model validation layer with diagnostics that are not part
of the primary backtest: segment-level calibration and month-block bootstrap
confidence intervals. It intentionally treats the outputs as POC diagnostics,
not as a new model-selection loop.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score


ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = ROOT / "docs" / "assets" / "hybrid_point7" / "hybrid_model_input_predictions.csv"
DYNAMIC_ALPHA_PATH = ROOT / "docs" / "assets" / "hybrid_point7" / "hybrid_dynamic_alpha_predictions.csv"
OUTPUT_DIR = ROOT / "docs" / "assets" / "validation_point10"
GENERATED_MD = ROOT / "docs" / "whitepaper" / "appendix" / "generated" / "10_segment_calibration_block_bootstrap_autogenerated.md"

RANDOM_SEED = 42
BOOTSTRAP_ITERATIONS = 2000
EV_THRESHOLD = 0.05
TAX_RATE = 0.12
SLIPPAGE = 0.01

TIER1_KEYWORDS = (
    "LEC",
    "LCS",
    "LTA",
    "LCK",
    "LPL",
    "European Championship",
    "Championship Series",
    "Champions Korea",
    "Pro League",
    "Mid-Season Invitational",
    "Mid Season Invitational",
    "First Stand",
    "World Championship",
    "Mistrzostwa Świata",
)


@dataclass(frozen=True)
class Candidate:
    """Probability candidate used in diagnostics.

    Attributes:
        name: Human-readable candidate name.
        column: DataFrame column containing team-1 win probability.
    """

    name: str
    column: str


def configure_style() -> None:
    """Configure a consistent plotting style."""

    sns.set_theme(style="whitegrid", context="talk")
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 300,
            "axes.titleweight": "bold",
            "axes.titlesize": 14,
            "axes.labelsize": 11,
        }
    )


def safe_logit(probability: pd.Series | np.ndarray) -> np.ndarray:
    """Return a numerically stable logit transform.

    Args:
        probability: Probability vector.

    Returns:
        Logit-transformed vector.
    """

    clipped = np.clip(np.asarray(probability, dtype=float), 1e-6, 1 - 1e-6)
    return np.log(clipped / (1 - clipped))


def sigmoid(value: np.ndarray) -> np.ndarray:
    """Return sigmoid transformation for a numeric vector.

    Args:
        value: Input vector.

    Returns:
        Sigmoid-transformed values.
    """

    return 1 / (1 + np.exp(-value))


def apply_temperature(probability: pd.Series | np.ndarray, temperature: float) -> np.ndarray:
    """Apply temperature scaling to binary probabilities.

    Args:
        probability: Base probabilities.
        temperature: Temperature value. Values below one sharpen predictions.

    Returns:
        Temperature-scaled probabilities.
    """

    return sigmoid(safe_logit(probability) / temperature)


def calculate_ece(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 10) -> float:
    """Calculate Expected Calibration Error.

    Args:
        y_true: Binary target values.
        y_prob: Predicted probabilities.
        n_bins: Number of equal-width calibration bins.

    Returns:
        Expected Calibration Error.
    """

    bins = np.linspace(0, 1, n_bins + 1)
    ece = 0.0
    for lower, upper in zip(bins[:-1], bins[1:]):
        mask = (y_prob > lower) & (y_prob <= upper)
        if mask.mean() > 0:
            ece += abs(y_prob[mask].mean() - y_true[mask].mean()) * mask.mean()
    return float(ece)


def is_tier1(tournament: object) -> bool:
    """Classify tournament into Tier 1 using the main EDA keyword logic.

    Args:
        tournament: Tournament name.

    Returns:
        True if tournament is classified as Tier 1.
    """

    text = str(tournament)
    if "Pro League" in text and not any(marker in text for marker in ("Oceanic", "Continental")):
        return True
    return any(keyword in text for keyword in TIER1_KEYWORDS)


def load_dataset() -> pd.DataFrame:
    """Load and enrich the hybrid input dataset.

    Returns:
        Dataset with candidate probability columns and segment labels.
    """

    data = pd.read_csv(INPUT_PATH)
    data["date"] = pd.to_datetime(data["date"])
    data = data.sort_values("date").reset_index(drop=True)

    dynamic = pd.read_csv(DYNAMIC_ALPHA_PATH, usecols=["golgg_match_id", "prob_dynamic_hybrid"])
    data = data.merge(dynamic, on="golgg_match_id", how="left").copy()

    data["prob_model_t060"] = apply_temperature(data["prob_model"], 0.60)
    data["prob_hybrid_a048_t060"] = 0.48 * data["prob_model_t060"] + 0.52 * data["prob_market_open"]
    data["prob_hybrid_dynamic"] = data["prob_dynamic_hybrid"].fillna(data["prob_hybrid_a048_t060"])

    data["year"] = data["date"].dt.year.astype(str)
    data["month"] = data["date"].dt.to_period("M").astype(str)
    data["bon_segment"] = "Bo" + data["BoN"].astype(str)
    data["tier_segment"] = np.where(data["tournament"].apply(is_tier1), "Tier 1", "Regional / ERL")

    favorite_prob = np.maximum(data["prob_market_open"], 1 - data["prob_market_open"])
    data["market_favorite_bucket"] = pd.cut(
        favorite_prob,
        bins=[0.5, 0.6, 0.7, 0.8, 1.0],
        labels=["50-60%", "60-70%", "70-80%", "80-100%"],
        include_lowest=True,
    ).astype(str)
    return data


def metric_row(data: pd.DataFrame, probability: np.ndarray) -> dict[str, float | int]:
    """Calculate probability metrics for a subset.

    Args:
        data: Evaluation subset.
        probability: Team-1 probability vector.

    Returns:
        Dictionary with probability metrics.
    """

    y_true = data["y_true"].to_numpy(dtype=int)
    y_prob = np.asarray(probability, dtype=float)
    row: dict[str, float | int] = {
        "n": int(len(data)),
        "mean_pred": float(np.mean(y_prob)),
        "observed_rate": float(np.mean(y_true)),
        "brier": float(brier_score_loss(y_true, y_prob)),
        "ece": calculate_ece(y_true, y_prob),
    }
    if len(np.unique(y_true)) == 2:
        row["auc"] = float(roc_auc_score(y_true, y_prob))
        row["logloss"] = float(log_loss(y_true, y_prob, labels=[0, 1]))
    else:
        row["auc"] = np.nan
        row["logloss"] = np.nan
    return row


def calculate_segment_calibration(data: pd.DataFrame, candidates: list[Candidate]) -> pd.DataFrame:
    """Calculate calibration metrics by segment.

    Args:
        data: Enriched evaluation dataset.
        candidates: Candidate probability definitions.

    Returns:
        Segment-level calibration metrics.
    """

    segment_columns = {
        "overall": None,
        "year": "year",
        "BoN": "bon_segment",
        "tier": "tier_segment",
        "market_favorite": "market_favorite_bucket",
    }
    rows: list[dict[str, float | int | str]] = []
    for candidate in candidates:
        for segment_type, column in segment_columns.items():
            groups = [("All", data)] if column is None else data.groupby(column, observed=True)
            for segment, subset in groups:
                if len(subset) < 50:
                    continue
                metrics = metric_row(subset, subset[candidate.column].to_numpy(dtype=float))
                rows.append(
                    {
                        "candidate": candidate.name,
                        "segment_type": segment_type,
                        "segment": str(segment),
                        **metrics,
                    }
                )
    return pd.DataFrame(rows)


def calculate_calibration_bins(data: pd.DataFrame, candidates: list[Candidate]) -> pd.DataFrame:
    """Calculate reliability-curve bins for each candidate.

    Args:
        data: Evaluation dataset.
        candidates: Candidate probability definitions.

    Returns:
        DataFrame with calibration-bin statistics.
    """

    rows: list[dict[str, float | int | str]] = []
    bins = np.linspace(0, 1, 11)
    labels = [f"{lower:.1f}-{upper:.1f}" for lower, upper in zip(bins[:-1], bins[1:])]
    for candidate in candidates:
        temp = data[["y_true", candidate.column]].copy()
        temp["bin"] = pd.cut(temp[candidate.column], bins=bins, labels=labels, include_lowest=True)
        for bin_label, subset in temp.groupby("bin", observed=True):
            if len(subset) == 0:
                continue
            rows.append(
                {
                    "candidate": candidate.name,
                    "bin": str(bin_label),
                    "n": int(len(subset)),
                    "avg_pred": float(subset[candidate.column].mean()),
                    "observed_rate": float(subset["y_true"].mean()),
                    "abs_error": float(abs(subset[candidate.column].mean() - subset["y_true"].mean())),
                }
            )
    return pd.DataFrame(rows)


def unit_stake_bets(data: pd.DataFrame, probability: np.ndarray) -> pd.DataFrame:
    """Create unit-stake bets selected by the EV rule.

    Args:
        data: Match dataset.
        probability: Team-1 probability vector.

    Returns:
        Selected bet rows with unit-stake profit and CLV.
    """

    rows: list[dict[str, float | int | str]] = []
    for idx, (_, row) in enumerate(data.iterrows()):
        prob_t1 = float(probability[idx])
        prob_t2 = 1 - prob_t1
        odds_t1 = float(row["best_open_t1"])
        odds_t2 = float(row["best_open_t2"])
        if np.isnan(odds_t1) or np.isnan(odds_t2):
            continue
        ev_t1 = prob_t1 * odds_t1 * (1 - TAX_RATE) - 1
        ev_t2 = prob_t2 * odds_t2 * (1 - TAX_RATE) - 1
        if ev_t1 > ev_t2 and ev_t1 > EV_THRESHOLD:
            side = "t1"
            selected_odds = odds_t1
            close_odds = float(row["best_close_t1"])
            is_win = int(row["y_true"]) == 1
            selected_ev = ev_t1
        elif ev_t2 > EV_THRESHOLD:
            side = "t2"
            selected_odds = odds_t2
            close_odds = float(row["best_close_t2"])
            is_win = int(row["y_true"]) == 0
            selected_ev = ev_t2
        else:
            continue

        execution_odds = selected_odds * (1 - SLIPPAGE)
        profit = execution_odds * (1 - TAX_RATE) - 1 if is_win else -1
        clv = (selected_odds / close_odds - 1) * 100 if close_odds > 0 else np.nan
        rows.append(
            {
                "month": row["month"],
                "side": side,
                "profit_unit": float(profit),
                "selected_ev": float(selected_ev),
                "clv_pct": float(clv),
                "is_win": int(is_win),
            }
        )
    return pd.DataFrame(rows)


def block_bootstrap(data: pd.DataFrame, candidates: list[Candidate]) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Run month-block bootstrap for probability and unit-bet metrics.

    Args:
        data: Evaluation dataset, usually 2024+.
        candidates: Candidate probability definitions.

    Returns:
        Tuple with bootstrap confidence intervals and full bootstrap draws.
    """

    rng = np.random.default_rng(RANDOM_SEED)
    data = data.reset_index(drop=True)
    months = np.array(sorted(data["month"].unique()))
    month_indices = {
        month: np.flatnonzero(data["month"].to_numpy() == month)
        for month in months
    }
    ci_rows: list[dict[str, float | int | str]] = []
    draw_rows: list[dict[str, float | int | str]] = []

    for candidate in candidates:
        bets = unit_stake_bets(data, data[candidate.column].to_numpy(dtype=float))
        bets = bets.reset_index(drop=True)
        bet_month_indices = {
            month: np.flatnonzero(bets["month"].to_numpy() == month)
            for month in months
        }
        y_all = data["y_true"].to_numpy(dtype=int)
        prob_all = data[candidate.column].to_numpy(dtype=float)
        for iteration in range(BOOTSTRAP_ITERATIONS):
            sampled_months = rng.choice(months, size=len(months), replace=True)
            sample_idx = np.concatenate([month_indices[month] for month in sampled_months])
            sample_prob = prob_all[sample_idx]
            y_true = y_all[sample_idx]
            draw: dict[str, float | int | str] = {
                "candidate": candidate.name,
                "iteration": iteration,
                "logloss": float(log_loss(y_true, sample_prob, labels=[0, 1])),
                "brier": float(brier_score_loss(y_true, sample_prob)),
                "ece": calculate_ece(y_true, sample_prob),
            }
            if len(np.unique(y_true)) == 2:
                draw["auc"] = float(roc_auc_score(y_true, sample_prob))
            else:
                draw["auc"] = np.nan

            if len(bets) > 0:
                bet_idx = np.concatenate([bet_month_indices[month] for month in sampled_months])
                if len(bet_idx) > 0:
                    draw["unit_yield_pct"] = float(bets.loc[bet_idx, "profit_unit"].mean() * 100)
                    draw["avg_clv_pct"] = float(bets.loc[bet_idx, "clv_pct"].mean())
                    draw["bets"] = int(len(bet_idx))
                else:
                    draw["unit_yield_pct"] = np.nan
                    draw["avg_clv_pct"] = np.nan
                    draw["bets"] = 0
            draw_rows.append(draw)

        candidate_draws = pd.DataFrame([row for row in draw_rows if row["candidate"] == candidate.name])
        for metric in ["auc", "logloss", "brier", "ece", "unit_yield_pct", "avg_clv_pct", "bets"]:
            values = candidate_draws[metric].dropna().to_numpy(dtype=float)
            ci_rows.append(
                {
                    "candidate": candidate.name,
                    "metric": metric,
                    "mean": float(np.mean(values)),
                    "p05": float(np.quantile(values, 0.05)),
                    "p50": float(np.quantile(values, 0.50)),
                    "p95": float(np.quantile(values, 0.95)),
                }
            )
    return pd.DataFrame(ci_rows), pd.DataFrame(draw_rows)


def save_segment_ece_plot(segment_df: pd.DataFrame) -> None:
    """Save segment ECE heatmap for key candidates.

    Args:
        segment_df: Segment metric DataFrame.
    """

    subset = segment_df[
        (segment_df["segment_type"].isin(["BoN", "tier", "market_favorite"]))
        & (segment_df["candidate"].isin(["Metamodel T=0.60", "Hybrid a=0.48 T=0.60", "Dynamic alpha hybrid"]))
    ].copy()
    subset["row"] = subset["segment_type"] + ": " + subset["segment"]
    pivot = subset.pivot(index="row", columns="candidate", values="ece")
    plt.figure(figsize=(10, 6))
    sns.heatmap(pivot, annot=True, fmt=".3f", cmap="YlOrRd", linewidths=0.5)
    plt.title("Segment calibration — ECE by segment and candidate")
    plt.xlabel("")
    plt.ylabel("")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "segment_calibration_ece_heatmap.png", bbox_inches="tight")
    plt.close()


def save_bootstrap_plot(ci_df: pd.DataFrame) -> None:
    """Save block bootstrap confidence interval plot.

    Args:
        ci_df: Bootstrap confidence interval summary.
    """

    subset = ci_df[ci_df["metric"].isin(["logloss", "unit_yield_pct", "avg_clv_pct"])].copy()
    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    for ax, metric in zip(axes, ["logloss", "unit_yield_pct", "avg_clv_pct"]):
        temp = subset[subset["metric"] == metric].sort_values("p50")
        y_pos = np.arange(len(temp))
        ax.errorbar(
            temp["p50"],
            y_pos,
            xerr=[temp["p50"] - temp["p05"], temp["p95"] - temp["p50"]],
            fmt="o",
            capsize=4,
        )
        ax.set_yticks(y_pos)
        ax.set_yticklabels(temp["candidate"])
        ax.set_title(metric)
        ax.grid(axis="x", linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "block_bootstrap_ci.png", bbox_inches="tight")
    plt.close()


def write_generated_markdown(segment_df: pd.DataFrame, ci_df: pd.DataFrame) -> None:
    """Write an autogenerated Obsidian appendix note.

    Args:
        segment_df: Segment calibration summary.
        ci_df: Block bootstrap confidence intervals.
    """

    overall = segment_df[segment_df["segment_type"] == "overall"].copy()
    overall = overall[["candidate", "n", "auc", "logloss", "brier", "ece"]]
    key_ci = ci_df[ci_df["metric"].isin(["logloss", "unit_yield_pct", "avg_clv_pct"])].copy()
    key_ci["ci_90"] = key_ci.apply(lambda row: f"{row['p05']:.4f} — {row['p95']:.4f}", axis=1)
    key_ci = key_ci[["candidate", "metric", "p50", "ci_90"]]

    content = f"""---
type: generated-experiment-log
tags:
  - whitepaper
  - calibration
  - block-bootstrap
  - robustness
project: inzynierka
date: 2026-05-01
status: generated
---

# Segmentowa kalibracja i block bootstrap

> [!abstract]
> Eksperyment sprawdza, czy kandydaci probabilistyczni są skalibrowani nie tylko globalnie, ale również w segmentach: BoN, tier rozgrywek, rok oraz siła faworyta według rynku. Druga część używa month-block bootstrapu, aby oszacować niepewność LogLoss, Brier, ECE oraz unit-stake Yield/CLV bez zakładania pełnej niezależności pojedynczych meczów.

## Konfiguracja

| Element | Wartość |
|---|---|
| Dataset | `docs/assets/hybrid_point7/hybrid_model_input_predictions.csv` |
| Zakres bootstrapu | `2024+` |
| Blok bootstrapu | miesiąc kalendarzowy |
| Iteracje | `{BOOTSTRAP_ITERATIONS}` |
| EV threshold dla unit-stake bets | `{EV_THRESHOLD:.2f}` |
| Tax / slippage | `{TAX_RATE:.0%}` / `{SLIPPAGE:.0%}` |
| Seed | `{RANDOM_SEED}` |

## Wyniki globalne

{overall.to_markdown(index=False, floatfmt='.5f')}

## Wizualizacje

![[assets/validation_point10/segment_calibration_ece_heatmap.png]]

![[assets/validation_point10/block_bootstrap_ci.png]]

## Block bootstrap — 90% CI

{key_ci.to_markdown(index=False, floatfmt='.4f')}

> [!important]
> Block bootstrap w tej wersji służy do oceny niepewności metryk probabilistycznych oraz unit-stake Yield/CLV. Nie zastępuje pełnej symulacji bankrolla, ponieważ losowanie bloków zmienia chronologiczną ścieżkę kapitału i nie daje wiarygodnego MaxDD.

## Wniosek

Segmentowa kalibracja pozwala oddzielić dwa pytania: czy kandydat ma dobrą średnią jakość probabilistyczną oraz czy nie traci kalibracji w konkretnych segmentach. Block bootstrap dodaje informację o niepewności wyniku w blokach czasowych, co jest bardziej konserwatywne niż traktowanie każdego meczu jako niezależnej obserwacji.
"""
    GENERATED_MD.write_text(content, encoding="utf-8")


def main() -> None:
    """Run segment calibration and block bootstrap diagnostics."""

    configure_style()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_MD.parent.mkdir(parents=True, exist_ok=True)

    data = load_dataset()
    candidates = [
        Candidate("Market Open", "prob_market_open"),
        Candidate("Metamodel T=1.00", "prob_model"),
        Candidate("Metamodel T=0.60", "prob_model_t060"),
        Candidate("Hybrid a=0.48 T=0.60", "prob_hybrid_a048_t060"),
        Candidate("Dynamic alpha hybrid", "prob_hybrid_dynamic"),
    ]

    segment_df = calculate_segment_calibration(data, candidates)
    bins_df = calculate_calibration_bins(data, candidates)
    bootstrap_scope = data[data["date"] >= pd.Timestamp("2024-01-01")].copy()
    ci_df, draw_df = block_bootstrap(bootstrap_scope, candidates)

    segment_df.to_csv(OUTPUT_DIR / "segment_calibration_summary.csv", index=False)
    bins_df.to_csv(OUTPUT_DIR / "calibration_bins.csv", index=False)
    ci_df.to_csv(OUTPUT_DIR / "block_bootstrap_ci.csv", index=False)
    draw_df.to_csv(OUTPUT_DIR / "block_bootstrap_draws.csv", index=False)

    save_segment_ece_plot(segment_df)
    save_bootstrap_plot(ci_df)
    write_generated_markdown(segment_df, ci_df)

    print("Segment calibration and block bootstrap completed.")
    print(f"Artifacts: {OUTPUT_DIR}")
    print(f"Generated note: {GENERATED_MD}")


if __name__ == "__main__":
    main()
