"""Generate hybrid model experiments for whitepaper Chapter 7.

The script uses the working metamodel configuration selected in Chapter 6:
player-only ratings + uncertainty + full rolling context W50 + shallow Optuna
LightGBM + update interval 1000 + input masking 0.1. It then blends the
out-of-sample metamodel probabilities with opening market probabilities.

All evaluation rows are restricted to matches present in ``odds.csv`` because
the hybrid model is an operational betting-stage component.
"""

from __future__ import annotations

import sys
import json
from collections import deque
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from lightgbm import LGBMClassifier
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import brier_score_loss, log_loss, roc_auc_score
from tqdm import tqdm


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.analysis.probability_metrics import calculate_ece
ASSETS_DIR = PROJECT_ROOT / "docs" / "assets" / "hybrid_point7"
REPORT_PATH = PROJECT_ROOT / "docs" / "whitepaper" / "07_hybrid_model_autogenerated.md"
TARGET = "y_true"
CONTEXT_WINDOW = 50
UPDATE_INTERVAL = 1000
MASK_RATE = 0.1
ALPHAS = np.round(np.linspace(0.0, 1.0, 51), 2)
BOOKMAKERS = ["betclic", "betfan", "efortuna", "lv_bet", "sts", "superbet"]


BASE_FEATURES = [
    "player_elo",
    "player_gl",
    "player_ts",
    "player_os",
    "player_pl",
    "player_tm",
    "player_elo_min1",
    "player_elo_min2",
    "player_gl_max1",
    "player_gl_max2",
    "player_gl_rd_avg1",
    "player_gl_rd_avg2",
    "player_ts_sigma_avg1",
    "player_ts_sigma_avg2",
    "player_os_sigma_avg1",
    "player_os_sigma_avg2",
    "player_pl_sigma_avg1",
    "player_pl_sigma_avg2",
    "player_tm_sigma_avg1",
    "player_tm_sigma_avg2",
]

ROLLING_FULL_FEATURES = [
    "t1_rolling_win_rate",
    "t2_rolling_win_rate",
    "t1_rolling_kills",
    "t2_rolling_kills",
    "t1_rolling_deaths",
    "t2_rolling_deaths",
    "t1_rolling_gd15",
    "t2_rolling_gd15",
    "t1_rolling_dpm",
    "t2_rolling_dpm",
    "t1_rolling_vspm",
    "t2_rolling_vspm",
]

FEATURES = BASE_FEATURES + ROLLING_FULL_FEATURES


def configure_plot_style() -> None:
    """Configure thesis-friendly chart style."""

    sns.set_theme(style="whitegrid", context="talk")
    plt.rcParams.update(
        {
            "figure.dpi": 120,
            "savefig.dpi": 300,
            "axes.titleweight": "bold",
            "axes.titlesize": 14,
            "axes.labelsize": 11,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
        }
    )


def optuna_params() -> dict[str, object]:
    """Return corrected Optuna LightGBM parameters from Chapter 6."""

    return {
        "max_depth": 2,
        "num_leaves": 3,
        "learning_rate": 0.0495484856620236,
        "n_estimators": 415,
        "min_child_samples": 65,
        "subsample": 0.6423308984276832,
        "colsample_bytree": 0.8371970895768155,
        "reg_alpha": 0.0026379865214127248,
        "reg_lambda": 4.578052284019224e-08,
        "verbosity": -1,
        "random_state": 42,
    }


def odds_to_prob(o1: float, o2: float) -> float:
    """Convert paired decimal odds to no-vig probability for team 1."""

    if pd.isna(o1) or pd.isna(o2) or o1 <= 1 or o2 <= 1:
        return np.nan
    margin = 1 / o1 + 1 / o2
    return float((1 / o1) / margin)


def default_team_stats() -> dict[str, float]:
    """Return neutral rolling defaults for teams without history."""

    return {
        "win_rate": 0.5,
        "kills": 12.0,
        "deaths": 12.0,
        "gd15": 0.0,
        "dpm": 1800.0,
        "vspm": 7.0,
    }


def safe_stat(player: dict[str, Any], key: str) -> float:
    """Read a numeric player statistic with zero fallback."""

    value = player.get("stats", {}).get(key, 0.0)
    return float(value or 0.0)


def average_history(history: deque[dict[str, float]] | None) -> dict[str, float]:
    """Average historical team-game records."""

    if not history:
        return default_team_stats()
    rows = list(history)
    return {
        "win_rate": float(np.mean([row["win"] for row in rows])),
        "kills": float(np.mean([row["kills"] for row in rows])),
        "deaths": float(np.mean([row["deaths"] for row in rows])),
        "gd15": float(np.mean([row["gd15"] for row in rows])),
        "dpm": float(np.mean([row["dpm"] for row in rows])),
        "vspm": float(np.mean([row["vspm"] for row in rows])),
    }


def update_team_history(
    team_history: dict[str, deque[dict[str, float]]],
    team_id: str,
    game: dict[str, Any],
) -> None:
    """Append one completed game to a team's rolling history."""

    is_team_1 = str(game.get("t1_id")) == str(team_id)
    win = bool(game.get("t1_win")) if is_team_1 else bool(game.get("t2_win"))
    players_key = "t1_players" if is_team_1 else "t2_players"
    players = game.get(players_key, {}) or {}
    record = {
        "win": float(win),
        "kills": sum(safe_stat(player, "kills") for player in players.values()),
        "deaths": sum(safe_stat(player, "deaths") for player in players.values()),
        "dpm": sum(safe_stat(player, "dpm") for player in players.values()),
        "vspm": sum(safe_stat(player, "vspm") for player in players.values()),
        "gd15": sum(safe_stat(player, "gd@15") for player in players.values()),
    }
    if team_id not in team_history:
        team_history[team_id] = deque(maxlen=CONTEXT_WINDOW)
    team_history[team_id].append(record)


def generate_rolling_features() -> pd.DataFrame:
    """Generate leakage-safe W50 rolling context features from GOL.GG history."""

    with open(PROJECT_ROOT / "data" / "golgg_matches.json", "r", encoding="utf-8") as file:
        matches = json.load(file)
    matches.sort(key=lambda item: item["date"])

    team_history: dict[str, deque[dict[str, float]]] = {}
    rows: list[dict[str, object]] = []
    for match in tqdm(matches, desc="Rolling W50"):
        match_id = str(match["match_id"])
        team_1 = str(match["tid_1"])
        team_2 = str(match["tid_2"])
        t1_stats = average_history(team_history.get(team_1))
        t2_stats = average_history(team_history.get(team_2))
        row: dict[str, object] = {"golgg_match_id": match_id}
        for stat, value in t1_stats.items():
            row[f"t1_rolling_{stat}"] = value
        for stat, value in t2_stats.items():
            row[f"t2_rolling_{stat}"] = value
        rows.append(row)

        for game in match.get("games", []) or []:
            update_team_history(team_history, team_1, game)
            update_team_history(team_history, team_2, game)

    return pd.DataFrame(rows)


def add_best_open_close_odds(df: pd.DataFrame) -> pd.DataFrame:
    """Add best opening and closing odds for both teams."""

    result = df.copy()
    for stage in ["open", "close"]:
        t1_cols = [f"odds1_{bookmaker}_{stage}" for bookmaker in BOOKMAKERS]
        t2_cols = [f"odds2_{bookmaker}_{stage}" for bookmaker in BOOKMAKERS]
        result[f"best_{stage}_t1"] = result[t1_cols].max(axis=1)
        result[f"best_{stage}_t2"] = result[t2_cols].max(axis=1)
    return result


def load_operational_data() -> pd.DataFrame:
    """Load predictions, market odds and rolling context for odds-mapped matches."""

    predictions = pd.read_csv(PROJECT_ROOT / "data" / "golgg_y_predicts.csv")
    odds = pd.read_csv(PROJECT_ROOT / "data" / "odds.csv")
    rolling = generate_rolling_features()

    predictions["golgg_match_id"] = predictions["golgg_match_id"].astype(str)
    odds["golgg_match_id"] = odds["golgg_match_id"].astype(str)
    rolling["golgg_match_id"] = rolling["golgg_match_id"].astype(str)

    data = predictions.merge(odds, on="golgg_match_id", how="inner", suffixes=("", "_odds"))
    data = data.merge(rolling, on="golgg_match_id", how="inner")
    data["date"] = pd.to_datetime(data["date"])
    data["y_true"] = data["t1_win"].astype(int)
    data["prob_market_open"] = data.apply(
        lambda row: odds_to_prob(row["avg_open_home"], row["avg_open_away"]),
        axis=1,
    )
    data["prob_market_close"] = data.apply(
        lambda row: odds_to_prob(row["avg_odds_home"], row["avg_odds_away"]),
        axis=1,
    )
    data = add_best_open_close_odds(data)
    data = data[data["date"] >= pd.Timestamp("2020-01-01")].copy()
    return data.sort_values("date").reset_index(drop=True)


def generate_metamodel_predictions(data: pd.DataFrame) -> pd.DataFrame:
    """Generate out-of-sample metamodel predictions for the operational sample."""

    clean = data.dropna(subset=FEATURES + [TARGET, "prob_market_open"]).copy()
    clean = clean.sort_values("date").reset_index(drop=True)
    initial_train = clean[clean["date"] < pd.Timestamp("2021-01-01")].copy()
    test_pool = clean[clean["date"] >= pd.Timestamp("2021-01-01")].copy()
    if initial_train.empty or test_pool.empty:
        raise ValueError("Hybrid split produced empty train or test sample.")

    rng = np.random.default_rng(42)
    train_df = initial_train.copy()
    chunks: list[pd.DataFrame] = []
    params = optuna_params()

    for start in tqdm(range(0, len(test_pool), UPDATE_INTERVAL), desc="Metamodel WF"):
        test_chunk = test_pool.iloc[start : start + UPDATE_INTERVAL].copy()
        x_train = train_df[FEATURES].copy()
        x_train = x_train.mask(rng.random(x_train.shape) < MASK_RATE)
        model = LGBMClassifier(**params)
        model.fit(x_train, train_df[TARGET].astype(int))
        test_chunk["prob_model"] = np.clip(model.predict_proba(test_chunk[FEATURES])[:, 1], 0.001, 0.999)
        chunks.append(test_chunk)
        train_df = pd.concat([train_df, test_chunk], ignore_index=True)

    return pd.concat(chunks, ignore_index=True)


def blend_linear(p_model: pd.Series, p_market: pd.Series, alpha: float) -> np.ndarray:
    """Blend probabilities linearly."""

    return np.clip(alpha * p_model + (1 - alpha) * p_market, 0.001, 0.999).to_numpy()


def blend_logit(p_model: pd.Series, p_market: pd.Series, alpha: float) -> np.ndarray:
    """Blend probabilities in logit space."""

    eps = 1e-6
    model = np.clip(p_model.to_numpy(), eps, 1 - eps)
    market = np.clip(p_market.to_numpy(), eps, 1 - eps)
    logit_model = np.log(model / (1 - model))
    logit_market = np.log(market / (1 - market))
    blended_logit = alpha * logit_model + (1 - alpha) * logit_market
    return np.clip(1 / (1 + np.exp(-blended_logit)), 0.001, 0.999)


def fixed_stake_simulation(
    df: pd.DataFrame,
    probability: np.ndarray,
    initial_bankroll: float = 100.0,
    stake: float = 0.10,
    tax_rate: float = 0.12,
    slippage: float = 0.01,
    ev_threshold: float = 0.05,
) -> dict[str, float | int]:
    """Run fixed-stake EV selection on best opening odds.

    Args:
        df: Evaluation dataframe with best opening/closing odds.
        probability: Team-1 win probabilities.
        initial_bankroll: Diagnostic bankroll. The default 100 USD makes the
            bankroll path directly readable as an indexed capital curve.
        stake: Fixed stake per selected bet. The default 0.10 USD preserves the
            earlier 0.1% stake-to-bankroll diagnostic scale.
        tax_rate: Polish turnover tax rate.
        slippage: Execution slippage applied to opening odds.
        ev_threshold: Minimum EV required to place a bet.

    Returns:
        Financial and CLV summary metrics.
    """

    bankroll = initial_bankroll
    history = [bankroll]
    total_staked = 0.0
    total_profit = 0.0
    wins = 0
    bets = 0
    clv_values: list[float] = []
    net_multiplier = 1 - tax_rate

    for idx, row in df.reset_index(drop=True).iterrows():
        p_t1 = float(probability[idx])
        p_t2 = 1 - p_t1
        open_t1 = row["best_open_t1"]
        open_t2 = row["best_open_t2"]
        if pd.isna(open_t1) or pd.isna(open_t2):
            history.append(bankroll)
            continue

        ev_t1 = open_t1 * net_multiplier * p_t1 - 1
        ev_t2 = open_t2 * net_multiplier * p_t2 - 1
        if ev_t1 > ev_t2 and ev_t1 > ev_threshold:
            side = "t1"
            raw_odds = open_t1
            close_odds = row["best_close_t1"]
            is_win = int(row[TARGET] == 1)
        elif ev_t2 > ev_threshold:
            side = "t2"
            raw_odds = open_t2
            close_odds = row["best_close_t2"]
            is_win = int(row[TARGET] == 0)
        else:
            history.append(bankroll)
            continue

        if bankroll < stake:
            history.append(bankroll)
            continue

        execution_odds = max(1.01, raw_odds * (1 - slippage))
        profit = stake * execution_odds * net_multiplier - stake if is_win else -stake
        bankroll += profit
        total_staked += stake
        total_profit += profit
        wins += is_win
        bets += 1
        if pd.notna(close_odds) and close_odds > 0:
            # Positive CLV means the selected opening price was better than the
            # later closing price for the same side.
            clv_values.append(float((raw_odds - close_odds) / close_odds))
        history.append(bankroll)
        _ = side

    bankroll_array = np.array(history)
    peaks = np.maximum.accumulate(bankroll_array)
    drawdowns = (peaks - bankroll_array) / (peaks + 1e-9)
    return {
        "FinalBankroll": bankroll,
        "ROI": (bankroll - initial_bankroll) / initial_bankroll * 100,
        "Yield": total_profit / total_staked * 100 if total_staked > 0 else 0.0,
        "MaxDD": float(np.max(drawdowns) * 100),
        "Bets": bets,
        "WinRate": wins / bets * 100 if bets > 0 else 0.0,
        "AvgStake": stake if bets > 0 else 0.0,
        "CLV": float(np.mean(clv_values) * 100) if clv_values else 0.0,
    }


def fixed_stake_simulation_with_history(
    df: pd.DataFrame,
    probability: np.ndarray,
    variant: str,
    initial_bankroll: float = 100.0,
    stake: float = 0.10,
    tax_rate: float = 0.12,
    slippage: float = 0.01,
    ev_threshold: float = 0.05,
    odds_stage: str = "open",
) -> tuple[dict[str, float | int | str], pd.DataFrame]:
    """Run fixed-stake EV simulation and keep bankroll path.

    Args:
        df: Evaluation dataframe with best opening/closing odds.
        probability: Team-1 win probabilities.
        variant: Human-readable variant name stored in output history.
        initial_bankroll: Diagnostic bankroll. Default is 100 USD for readable
            bankroll-over-time plots.
        stake: Fixed stake per selected bet. Default 0.10 USD is the scaled
            equivalent of the previous 10 USD stake on a 10,000 USD bankroll.
        tax_rate: Polish turnover tax rate.
        slippage: Execution slippage applied to opening odds.
        ev_threshold: Minimum EV required to place a bet.
        odds_stage: Odds stage used for EV and execution, either ``open`` or
            ``close``. Closing odds are used only for last-moment benchmark
            simulations, not for the default operational hybrid.

    Returns:
        Tuple containing summary metrics and match-by-match bankroll history.
    """

    bankroll = initial_bankroll
    total_staked = 0.0
    total_profit = 0.0
    wins = 0
    bets = 0
    clv_values: list[float] = []
    net_multiplier = 1 - tax_rate
    history_rows: list[dict[str, object]] = []
    if odds_stage not in {"open", "close"}:
        raise ValueError("odds_stage must be either 'open' or 'close'.")
    odds_t1_column = f"best_{odds_stage}_t1"
    odds_t2_column = f"best_{odds_stage}_t2"

    for idx, row in df.reset_index(drop=True).iterrows():
        p_t1 = float(probability[idx])
        p_t2 = 1 - p_t1
        open_t1 = row[odds_t1_column]
        open_t2 = row[odds_t2_column]
        side = "none"
        raw_odds = np.nan
        close_odds = np.nan
        is_win = 0
        profit = 0.0
        selected_ev = np.nan
        bet_placed = False

        if pd.notna(open_t1) and pd.notna(open_t2):
            ev_t1 = open_t1 * net_multiplier * p_t1 - 1
            ev_t2 = open_t2 * net_multiplier * p_t2 - 1
            if ev_t1 > ev_t2 and ev_t1 > ev_threshold:
                side = "t1"
                raw_odds = open_t1
                close_odds = row["best_close_t1"]
                is_win = int(row[TARGET] == 1)
                selected_ev = ev_t1
            elif ev_t2 > ev_threshold:
                side = "t2"
                raw_odds = open_t2
                close_odds = row["best_close_t2"]
                is_win = int(row[TARGET] == 0)
                selected_ev = ev_t2

        if side != "none" and bankroll >= stake:
            execution_odds = max(1.01, float(raw_odds) * (1 - slippage))
            profit = stake * execution_odds * net_multiplier - stake if is_win else -stake
            bankroll += profit
            total_staked += stake
            total_profit += profit
            wins += is_win
            bets += 1
            bet_placed = True
            if pd.notna(close_odds) and close_odds > 0:
                clv_values.append(float((raw_odds - close_odds) / close_odds))

        history_rows.append(
            {
                "variant": variant,
                "date": row["date"],
                "match_index": idx,
                "bankroll": bankroll,
                "profit": profit,
                "bet_placed": bet_placed,
                "side": side,
                "selected_ev": selected_ev,
            }
        )

    bankroll_array = np.array([initial_bankroll] + [float(row["bankroll"]) for row in history_rows])
    peaks = np.maximum.accumulate(bankroll_array)
    drawdowns = (peaks - bankroll_array) / (peaks + 1e-9)
    summary: dict[str, float | int | str] = {
        "variant": variant,
        "FinalBankroll": bankroll,
        "ROI": (bankroll - initial_bankroll) / initial_bankroll * 100,
        "Yield": total_profit / total_staked * 100 if total_staked > 0 else 0.0,
        "MaxDD": float(np.max(drawdowns) * 100),
        "Bets": bets,
        "WinRate": wins / bets * 100 if bets > 0 else 0.0,
        "AvgStake": stake if bets > 0 else 0.0,
        "CLV": float(np.mean(clv_values) * 100) if clv_values else 0.0,
    }
    return summary, pd.DataFrame(history_rows)


def evaluate_probability(df: pd.DataFrame, probability: np.ndarray) -> dict[str, float | int]:
    """Evaluate statistical and fixed-stake financial metrics."""

    y_true = df[TARGET].astype(int).to_numpy()
    clipped = np.clip(probability, 0.001, 0.999)
    financial = fixed_stake_simulation(df, clipped)
    return {
        "AUC": roc_auc_score(y_true, clipped),
        "LogLoss": log_loss(y_true, clipped),
        "Brier": brier_score_loss(y_true, clipped),
        "ECE": calculate_ece(y_true, clipped),
        **financial,
    }


def static_alpha_sweep(df: pd.DataFrame) -> pd.DataFrame:
    """Evaluate linear and logit static alpha sweeps."""

    rows: list[dict[str, object]] = []
    for blend_type in ["linear", "logit"]:
        for alpha in ALPHAS:
            if blend_type == "linear":
                prob = blend_linear(df["prob_model"], df["prob_market_open"], float(alpha))
            else:
                prob = blend_logit(df["prob_model"], df["prob_market_open"], float(alpha))
            rows.append({"blend_type": blend_type, "alpha": float(alpha), **evaluate_probability(df, prob)})
    return pd.DataFrame(rows)


def choose_alpha_from_history(history: pd.DataFrame) -> float:
    """Select alpha from earlier out-of-sample history by LogLoss."""

    if len(history) < 500:
        return 0.5
    scores = []
    for alpha in ALPHAS:
        prob = blend_linear(history["prob_model"], history["prob_market_open"], float(alpha))
        scores.append((log_loss(history[TARGET].astype(int), prob), float(alpha)))
    return min(scores, key=lambda item: item[0])[1]


def dynamic_alpha_walk_forward(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Generate dynamic-alpha predictions using only earlier WF predictions."""

    chunks: list[pd.DataFrame] = []
    alpha_rows: list[dict[str, object]] = []
    history = pd.DataFrame(columns=df.columns)
    for start in range(0, len(df), UPDATE_INTERVAL):
        chunk = df.iloc[start : start + UPDATE_INTERVAL].copy()
        alpha = choose_alpha_from_history(history)
        chunk["dynamic_alpha"] = alpha
        chunk["prob_dynamic_hybrid"] = blend_linear(chunk["prob_model"], chunk["prob_market_open"], alpha)
        chunks.append(chunk)
        alpha_rows.append(
            {
                "block_start": str(chunk["date"].min().date()),
                "block_end": str(chunk["date"].max().date()),
                "alpha": alpha,
                "rows": len(chunk),
            }
        )
        history = pd.concat([history, chunk], ignore_index=True)

    return pd.concat(chunks, ignore_index=True), pd.DataFrame(alpha_rows)


def dynamic_alpha_elo_update(
    df: pd.DataFrame,
    k_factor: float = 0.02,
    initial_alpha: float = 0.5,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Generate online dynamic-alpha predictions with Elo-like updates.

    The alpha used for match ``i`` is known before the result. After observing
    the result, alpha is moved toward the source that had lower log loss:

    ``alpha_next = alpha + K * (loss_market - loss_model)``.

    If the model predicted the match better than the market, ``loss_model`` is
    smaller, so alpha increases. If the market was better, alpha decreases.

    Args:
        df: Chronological dataframe with model and market probabilities.
        k_factor: Update speed, analogous to an Elo K-factor.
        initial_alpha: Starting trust assigned to the metamodel.

    Returns:
        Tuple with predictions and per-match alpha history.
    """

    alpha = initial_alpha
    prediction_rows: list[dict[str, object]] = []
    history_rows: list[dict[str, object]] = []
    eps = 1e-6

    for idx, row in df.reset_index(drop=True).iterrows():
        p_model = float(np.clip(row["prob_model"], eps, 1 - eps))
        p_market = float(np.clip(row["prob_market_open"], eps, 1 - eps))
        y_true = int(row[TARGET])
        p_hybrid = float(np.clip(alpha * p_model + (1 - alpha) * p_market, 0.001, 0.999))

        model_loss = -(y_true * np.log(p_model) + (1 - y_true) * np.log(1 - p_model))
        market_loss = -(y_true * np.log(p_market) + (1 - y_true) * np.log(1 - p_market))
        alpha_next = float(np.clip(alpha + k_factor * (market_loss - model_loss), 0.0, 1.0))

        base_row = row.to_dict()
        base_row["elo_alpha"] = alpha
        base_row["prob_elo_dynamic_hybrid"] = p_hybrid
        prediction_rows.append(base_row)
        history_rows.append(
            {
                "date": row["date"],
                "match_index": idx,
                "k_factor": k_factor,
                "alpha_before": alpha,
                "alpha_after": alpha_next,
                "model_loss": model_loss,
                "market_loss": market_loss,
                "loss_advantage_model": market_loss - model_loss,
            }
        )
        alpha = alpha_next

    return pd.DataFrame(prediction_rows), pd.DataFrame(history_rows)


def elo_alpha_k_sweep(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Evaluate several Elo-like K-factors and return the best variant."""

    rows: list[dict[str, object]] = []
    predictions_by_k: dict[float, pd.DataFrame] = {}
    histories_by_k: dict[float, pd.DataFrame] = {}
    for k_factor in [0.0025, 0.005, 0.01, 0.02, 0.05, 0.075, 0.10]:
        pred_df, history_df = dynamic_alpha_elo_update(df, k_factor=k_factor)
        metrics = evaluate_probability(pred_df, pred_df["prob_elo_dynamic_hybrid"].to_numpy())
        rows.append({"k_factor": k_factor, **metrics})
        predictions_by_k[k_factor] = pred_df
        histories_by_k[k_factor] = history_df

    sweep = pd.DataFrame(rows).sort_values("LogLoss").reset_index(drop=True)
    best_k = float(sweep.iloc[0]["k_factor"])
    return sweep, predictions_by_k[best_k], histories_by_k[best_k]


def disagreement_buckets(df: pd.DataFrame, probability: np.ndarray) -> pd.DataFrame:
    """Evaluate hybrid performance by model-market disagreement bucket."""

    data = df.copy()
    data["prob_hybrid"] = probability
    data["abs_diff"] = (data["prob_model"] - data["prob_market_open"]).abs()
    data["bucket"] = pd.cut(
        data["abs_diff"],
        bins=[0.0, 0.05, 0.10, 0.20, 1.0],
        labels=["0.00–0.05", "0.05–0.10", "0.10–0.20", ">0.20"],
        include_lowest=True,
    )
    rows = []
    for bucket, group in data.groupby("bucket", observed=True):
        if len(group) < 50:
            continue
        rows.append({"bucket": str(bucket), "matches": len(group), **evaluate_probability(group, group["prob_hybrid"].to_numpy())})
    return pd.DataFrame(rows)


def calibrate_hybrid(df: pd.DataFrame, probability_column: str) -> pd.DataFrame:
    """Fit isotonic calibration on first half and evaluate on second half."""

    split_idx = len(df) // 2
    train = df.iloc[:split_idx]
    test = df.iloc[split_idx:].copy()
    calibrator = IsotonicRegression(out_of_bounds="clip")
    calibrator.fit(train[probability_column], train[TARGET].astype(int))
    test["prob_calibrated"] = np.clip(calibrator.transform(test[probability_column]), 0.001, 0.999)
    return test


def save_alpha_plots(alpha_df: pd.DataFrame) -> None:
    """Save alpha sensitivity plots."""

    linear = alpha_df[alpha_df["blend_type"] == "linear"].copy()
    fig, axes = plt.subplots(2, 3, figsize=(16, 8.5))
    plot_specs = [
        ("AUC", axes[0, 0], "#4c72b0"),
        ("LogLoss", axes[0, 1], "#dd8452"),
        ("ECE", axes[1, 0], "#55a868"),
        ("ROI", axes[0, 2], "#c44e52"),
        ("Yield", axes[1, 1], "#8172b3"),
        ("Bets", axes[1, 2], "#937860"),
    ]
    for metric, axis, color in plot_specs:
        sns.lineplot(data=linear, x="alpha", y=metric, marker="o", ax=axis, color=color)
        best_idx = linear[metric].idxmin() if metric in {"LogLoss", "ECE"} else linear[metric].idxmax()
        best_alpha = linear.loc[best_idx, "alpha"]
        axis.axvline(best_alpha, color=color, linestyle="--", alpha=0.55)
        axis.set_title(f"Alpha vs {metric}")
        axis.set_xlabel("Alpha — udział metamodelu")
    plt.tight_layout()
    plt.savefig(ASSETS_DIR / "hybrid_static_alpha_sensitivity.png", bbox_inches="tight")
    plt.close()

    plt.figure(figsize=(10, 5))
    ax = sns.lineplot(data=linear, x="alpha", y="ROI", marker="o", color="#c44e52")
    best_roi = linear.loc[linear["ROI"].idxmax()]
    best_logloss = linear.loc[linear["LogLoss"].idxmin()]
    ax.axvline(best_roi["alpha"], color="#c44e52", linestyle="--", alpha=0.65, label="best ROI")
    ax.axvline(best_logloss["alpha"], color="#4c72b0", linestyle=":", alpha=0.85, label="best LogLoss")
    ax.set_title("Alpha vs ROI — fixed stake diagnostic, EV > 5%")
    ax.set_xlabel("Alpha — udział metamodelu")
    ax.set_ylabel("ROI (%)")
    ax.legend()
    plt.tight_layout()
    plt.savefig(ASSETS_DIR / "hybrid_alpha_vs_roi.png", bbox_inches="tight")
    plt.close()


def save_dynamic_alpha_plot(alpha_history: pd.DataFrame) -> None:
    """Save dynamic alpha over time plot."""

    plt.figure(figsize=(11, 4.8))
    sns.lineplot(data=alpha_history, x="block_start", y="alpha", marker="o", color="#4c72b0")
    plt.xticks(rotation=35, ha="right")
    plt.ylim(-0.02, 1.02)
    plt.title("Dynamiczna alfa w kolejnych blokach walk-forward")
    plt.xlabel("Początek bloku")
    plt.ylabel("Alpha")
    plt.tight_layout()
    plt.savefig(ASSETS_DIR / "hybrid_dynamic_alpha_over_time.png", bbox_inches="tight")
    plt.close()


def save_elo_alpha_plot(elo_history: pd.DataFrame) -> None:
    """Save Elo-like dynamic alpha plot."""

    plot_df = elo_history.copy()
    plot_df["date"] = pd.to_datetime(plot_df["date"])
    plot_df["alpha_smooth"] = plot_df["alpha_before"].rolling(200, min_periods=1).mean()
    plt.figure(figsize=(11, 4.8))
    sns.lineplot(data=plot_df, x="date", y="alpha_before", color="#4c72b0", alpha=0.22, linewidth=0.8, label="alpha per match")
    sns.lineplot(data=plot_df, x="date", y="alpha_smooth", color="#c44e52", linewidth=2.2, label="rolling mean 200")
    plt.ylim(-0.02, 1.02)
    plt.title("Dynamiczna alfa aktualizowana jak rating Elo")
    plt.xlabel("Data")
    plt.ylabel("Alpha przed meczem")
    plt.legend()
    plt.tight_layout()
    plt.savefig(ASSETS_DIR / "hybrid_elo_alpha_over_time.png", bbox_inches="tight")
    plt.close()


def save_bankroll_plot(
    history_df: pd.DataFrame,
    output_name: str = "hybrid_bankroll_over_time.png",
    title: str = "Bankroll over time — fixed stake diagnostic, EV > 5%",
) -> None:
    """Save bankroll-over-time comparison for selected variants."""

    plot_df = history_df.copy()
    plot_df["date"] = pd.to_datetime(plot_df["date"])
    plt.figure(figsize=(12, 5.6))
    sns.lineplot(data=plot_df, x="date", y="bankroll", hue="variant", linewidth=2)
    plt.title(title)
    plt.xlabel("Data")
    plt.ylabel("Bankroll")
    plt.legend(title="Wariant", fontsize=9)
    plt.tight_layout()
    plt.savefig(ASSETS_DIR / output_name, bbox_inches="tight")
    plt.close()


def write_markdown_summary(
    alpha_df: pd.DataFrame,
    dynamic_metrics: dict[str, float | int],
    best_linear: pd.Series,
) -> None:
    """Write autogenerated Markdown experiment summary."""

    top_cols = ["blend_type", "alpha", "AUC", "LogLoss", "Brier", "ECE", "ROI", "Yield", "MaxDD", "Bets", "CLV"]
    lines = [
        "---",
        "type: experiment-report",
        "tags: [whitepaper, hybrid-model, alpha-sensitivity, walk-forward]",
        "project: inzynierka",
        "date: 2026-04-30",
        "status: autogenerated",
        "---",
        "",
        "# 07. Hybrid model autogenerated summary",
        "",
        "> [!abstract]",
        "> Static alpha sweep and leakage-safe dynamic-alpha walk-forward for the Chapter 6 working metamodel candidate.",
        "",
        "## Best static linear alpha by LogLoss",
        "",
        best_linear[top_cols].to_frame().T.to_markdown(index=False, floatfmt=".5f"),
        "",
        "## Dynamic alpha metrics",
        "",
        pd.DataFrame([dynamic_metrics]).to_markdown(index=False, floatfmt=".5f"),
        "",
        "## Static sweep",
        "",
        alpha_df[top_cols].sort_values(["blend_type", "LogLoss"]).head(12).to_markdown(index=False, floatfmt=".5f"),
        "",
    ]
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run Chapter 7 hybrid experiments."""

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    configure_plot_style()
    data = load_operational_data()
    model_df = generate_metamodel_predictions(data)
    model_df.to_csv(ASSETS_DIR / "hybrid_model_input_predictions.csv", index=False)

    alpha_df = static_alpha_sweep(model_df)
    alpha_df.to_csv(ASSETS_DIR / "hybrid_static_alpha_sweep.csv", index=False)
    save_alpha_plots(alpha_df)

    dynamic_df, alpha_history = dynamic_alpha_walk_forward(model_df)
    dynamic_df.to_csv(ASSETS_DIR / "hybrid_dynamic_alpha_predictions.csv", index=False)
    alpha_history.to_csv(ASSETS_DIR / "hybrid_dynamic_alpha_history.csv", index=False)
    save_dynamic_alpha_plot(alpha_history)

    dynamic_metrics = evaluate_probability(dynamic_df, dynamic_df["prob_dynamic_hybrid"].to_numpy())
    pd.DataFrame([{ "variant": "dynamic_alpha", **dynamic_metrics }]).to_csv(
        ASSETS_DIR / "hybrid_dynamic_alpha_metrics.csv",
        index=False,
    )

    elo_sweep, elo_dynamic_df, elo_history = elo_alpha_k_sweep(model_df)
    elo_sweep.to_csv(ASSETS_DIR / "hybrid_elo_alpha_k_sweep.csv", index=False)
    elo_dynamic_df.to_csv(ASSETS_DIR / "hybrid_elo_alpha_predictions.csv", index=False)
    elo_history.to_csv(ASSETS_DIR / "hybrid_elo_alpha_history.csv", index=False)
    save_elo_alpha_plot(elo_history)
    elo_metrics = evaluate_probability(elo_dynamic_df, elo_dynamic_df["prob_elo_dynamic_hybrid"].to_numpy())
    pd.DataFrame([{ "variant": "elo_dynamic_alpha", **elo_metrics }]).to_csv(
        ASSETS_DIR / "hybrid_elo_alpha_metrics.csv",
        index=False,
    )

    best_linear = alpha_df[alpha_df["blend_type"] == "linear"].sort_values("LogLoss").iloc[0]
    best_roi_linear = alpha_df[alpha_df["blend_type"] == "linear"].sort_values("ROI", ascending=False).iloc[0]
    best_prob = blend_linear(model_df["prob_model"], model_df["prob_market_open"], float(best_linear["alpha"]))
    disagreement = disagreement_buckets(model_df, best_prob)
    disagreement.to_csv(ASSETS_DIR / "hybrid_disagreement_buckets.csv", index=False)

    best_roi_prob = blend_linear(
        model_df["prob_model"],
        model_df["prob_market_open"],
        float(best_roi_linear["alpha"]),
    )
    bankroll_summaries: list[dict[str, float | int | str]] = []
    bankroll_histories: list[pd.DataFrame] = []
    for variant, probability in [
        (f"static_logloss_alpha_{best_linear['alpha']:.2f}", best_prob),
        (f"static_roi_alpha_{best_roi_linear['alpha']:.2f}", best_roi_prob),
        ("block_dynamic_alpha", dynamic_df["prob_dynamic_hybrid"].to_numpy()),
        ("elo_dynamic_alpha", elo_dynamic_df["prob_elo_dynamic_hybrid"].to_numpy()),
    ]:
        summary, history = fixed_stake_simulation_with_history(model_df, probability, variant=variant)
        bankroll_summaries.append(summary)
        bankroll_histories.append(history)
    bankroll_summary_df = pd.DataFrame(bankroll_summaries)
    bankroll_history_df = pd.concat(bankroll_histories, ignore_index=True)
    bankroll_summary_df.to_csv(ASSETS_DIR / "hybrid_bankroll_summary.csv", index=False)
    bankroll_history_df.to_csv(ASSETS_DIR / "hybrid_bankroll_over_time.csv", index=False)
    save_bankroll_plot(bankroll_history_df)

    comparison_summaries: list[dict[str, float | int | str]] = []
    comparison_histories: list[pd.DataFrame] = []
    for variant, probability in [
        ("market_avg_open", model_df["prob_market_open"].to_numpy()),
        ("metamodel", model_df["prob_model"].to_numpy()),
        (f"best_hybrid_alpha_{best_roi_linear['alpha']:.2f}", best_roi_prob),
    ]:
        summary, history = fixed_stake_simulation_with_history(model_df, probability, variant=variant)
        comparison_summaries.append(summary)
        comparison_histories.append(history)
    comparison_summary_df = pd.DataFrame(comparison_summaries)
    comparison_history_df = pd.concat(comparison_histories, ignore_index=True)
    comparison_summary_df.to_csv(
        ASSETS_DIR / "hybrid_bankroll_model_market_hybrid_100_summary.csv",
        index=False,
    )
    comparison_history_df.to_csv(
        ASSETS_DIR / "hybrid_bankroll_model_market_hybrid_100.csv",
        index=False,
    )
    save_bankroll_plot(
        comparison_history_df,
        output_name="hybrid_bankroll_model_market_hybrid_100.png",
        title="Bankroll over time — Market Avg vs Metamodel vs Best Hybrid ($100 start)",
    )

    modern_df = model_df[model_df["date"] >= pd.Timestamp("2024-01-01")].copy()
    modern_best_roi_prob = blend_linear(
        modern_df["prob_model"],
        modern_df["prob_market_open"],
        float(best_roi_linear["alpha"]),
    )
    modern_summaries: list[dict[str, float | int | str]] = []
    modern_histories: list[pd.DataFrame] = []
    for variant, probability, odds_stage in [
        ("market_avg_open_2024", modern_df["prob_market_open"].to_numpy(), "open"),
        ("market_avg_close_2024", modern_df["prob_market_close"].to_numpy(), "close"),
        ("metamodel_2024", modern_df["prob_model"].to_numpy(), "open"),
        (f"best_hybrid_alpha_{best_roi_linear['alpha']:.2f}_2024", modern_best_roi_prob, "open"),
    ]:
        summary, history = fixed_stake_simulation_with_history(
            modern_df,
            probability,
            variant=variant,
            initial_bankroll=100.0,
            stake=10.0,
            odds_stage=odds_stage,
        )
        modern_summaries.append(summary)
        modern_histories.append(history)
    modern_summary_df = pd.DataFrame(modern_summaries)
    modern_history_df = pd.concat(modern_histories, ignore_index=True)
    modern_summary_df.to_csv(
        ASSETS_DIR / "hybrid_bankroll_model_market_hybrid_2024_fixed10_summary.csv",
        index=False,
    )
    modern_history_df.to_csv(
        ASSETS_DIR / "hybrid_bankroll_model_market_hybrid_2024_fixed10.csv",
        index=False,
    )
    save_bankroll_plot(
        modern_history_df,
        output_name="hybrid_bankroll_model_market_hybrid_2024_fixed10.png",
        title="Bankroll 2024–now — Market Avg vs Metamodel vs Best Hybrid ($10 fixed stake)",
    )

    model_df["prob_best_static_linear"] = best_prob
    calibrated_test = calibrate_hybrid(model_df, "prob_best_static_linear")
    calibrated_metrics = evaluate_probability(calibrated_test, calibrated_test["prob_calibrated"].to_numpy())
    pd.DataFrame([{ "variant": "static_best_isotonic_second_half", **calibrated_metrics }]).to_csv(
        ASSETS_DIR / "hybrid_calibrated_holdout_metrics.csv",
        index=False,
    )

    write_markdown_summary(alpha_df, dynamic_metrics, best_linear)

    print("\n=== HYBRID CHAPTER 7 RESULTS ===")
    print("Best static linear alpha by LogLoss:")
    print(best_linear.to_string())
    print("\nDynamic alpha metrics:")
    print(pd.Series(dynamic_metrics).to_string())
    print("\nElo-like dynamic alpha metrics:")
    print(pd.Series(elo_metrics).to_string())
    print("\nSaved artefacts to:", ASSETS_DIR)


if __name__ == "__main__":
    main()
